### ISSUE TITLE
Add `office type` and `Location` in `IFRC Presence`

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#1009]
## Task description
- `IFRC Presence`: Add `Office type` (field `officetype` in the API response) (e.g. `Headquarters`, `Regional Office`, `Country Cluster`, `Representative Office`), and location (field `city` in the API response)

**Comment by tovari** [comment]
@udaynwa, please hide the phone number field for now. I'm not sure, if we can publish it.
Please also hide Source: FDRS as it is not the case anymore.
Thanks!
