### ISSUE TITLE
Remove and replace items in `Membership coordination`

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#1010]
## Task description
- `Membership coordination`: remove `Engaged`, `Accountable`, and `Trusted`, and instead add `Enabling functions`. Therefore the total list should be: `Climate`, `Crisis`, `Health`, `Migration`, `Inclusion`, and `Enabling functions`.

**Comment by udaynwa** [comment]
@tovari , adding a couple of questions here: 

## DEV questions
- How do we handle the previous data? 
- How or where do we get the new data from?

**Comment by tovari** [comment]
We have a new Master sheet file with new structure:

Membership coordination:
Climate - AI
Crisis - AJ
Health - AK
Migration - AL
Inclusion - AM
Enabling Functions - AN

Strategic Priority (with the new labels #1008):
- Climate and environment - T
- Disasters and crisis - U
- Health and wellbeing - V
- Migration and displacement - W
- Values, power and inclusion - X
- Ongoing emergency operations - S

Key figures:
- Federation-Wide requested Amount - FB
- People targeted - Max of S - X range

Previous data will not be displayed.
[Master Data_2024 Planning.xlsx](https://github.com/IFRCGo/go-web-app/files/15399963/Master.Data_2024.Planning.xlsx)

**Comment by k9845** [comment]
@tovari What about the old `Membership coordination` and `Strategic Priority`  data? Do we migrate them to new one? Also for `Strategic Priority ` are we  just renaming the labels? If we are removing them, old data would be lost, and we will have data only for `2024` from above master sheet.
cc: @udaynwa

**Comment by tovari** [comment]
@k9845, we don't need to display or even store previous `Membership coordination` and `Strategic Priority` data. We only need to show the actual data (`2024`). Thanks!

**Comment by k9845** [comment]
@tovari We got following error while loading the new date from the excel sheet  for country `Afghanistan` and `Mayanmar`.

```bash
Missing NS in the database: {'Hong Kong Red Cross - branch of Red Cross Society of China'}
Missing NS in the database: {'Singapore Red Cross'}
````
cc: @samshara @udaynwa

**Comment by tovari** [comment]
[Master.Data_2024_Daniel19062024.Planning.xlsx](https://github.com/user-attachments/files/15900293/Master.Data_2024_Daniel19062024.Planning.xlsx)

This is the updated master sheet that handles the hong kong and singapore NS name issues
