### ISSUE TITLE
Printable Stories

### ISSUE THREAD

**Issue by roshni73** [IFRCGo/go-web-app#1024]
## Task Description
   Create story for  Printable component

### Acceptance criteria
-   Printable  should work on sidebar and canvas

#### Links
  staging
     - https://go-stage.ifrc.org/ 
  Figma
    - https://www.figma.com/file/myeW85ibN5p2SlnXcEpxFD/IFRC-GO---UI-Current---1?type=design&node-id=0-4957&mode=design&t=KwxbuoUQxqcLyZbG-0

**Comment by samshara** [comment]
I don't this is a singular component. We have multiple components under `Printable` folder. Maybe we should create stories for those components. Also, maybe we don't need those stories as they are used only in exports.
