### ISSUE TITLE
Parked Stories

### ISSUE THREAD

**Issue by roshni73** [IFRCGo/go-web-app#1035]
## Task Description
   Create story  of TopBanner for  Parked component 

### Acceptance criteria
-  TopBanner  should work on sidebar and canvas

#### Links
  staging
     - https://go-stage.ifrc.org/ 
  Figma
    - https://www.figma.com/file/myeW85ibN5p2SlnXcEpxFD/IFRC-GO---UI-Current---1?type=design&node-id=0-4957&mode=design&t=KwxbuoUQxqcLyZbG-0

**Comment by samshara** [comment]
We don't need to create story for `Parked` components.
