### ISSUE TITLE
Document the proposed flow for Local Units data update

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#1122]

**Comment by udaynwa** [comment]
## Notes from 24th May, 2024 meeting

- How frequently is the data imported using the excel?
	- 2 use-cases
		- Branches/local units are updating the attributes of the local units 
		  logseq.order-list-type:: number
		- When the NS are collecting the data and are updating in batch
		  logseq.order-list-type:: number
	- Not more than once a year per NS
- Will it be easier to import by Country?
- UI for importing required or not?
	- Not required. Okay from the backend
		- If we are to do from the backend, we will need to be more careful on the validation of the data. We should be more careful on the excel files
	- Preferred solution: Do it frontend.
		- Will add +1 validation layer
		- Less back&forth during the data validation
	- Matching the old data with the updated data?
		- Can use the unique identifier to link
- Possibility to make the import template more strict?
	- Generating the import template is useful - Daniel
		- Can add choice fields to let users select from the pre-defined values
- Multiple similar fields in Healthcare and Administrative which can be merged
	- Eg: Focal point contact details
- Branch name is missing in a lot of rows in the import excel file
	- These are not imported right now
	- Daniel
		- David should clean the data and add the missing type, if possible
	- Ankit
		- If we want to import the added data, we need to only add the previously missing fields
- From Daniel
	- Phone numbers. Publicly or not?
		- Right now, showing only for the logged-in users

## Action item
- [ ] Documentation of how this will work. Our proposals

		- Also include the similar fields related ideas

cc @samshara

**Comment by tnagorra** [comment]
Closing this issue as the flow has been updated and finalized.
