### ISSUE TITLE
[PROD] New field report notification email link to the site 

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#1185]
New FR notification email link to GO 'Open in GO' is incorrectly points to the #surge tab instead of the operations tab.

E.g. link in the notification email: https://go.ifrc.org/emergencies/7028#surge

It should be:
https://go.ifrc.org/emergencies/7028

**Comment by szabozoltan69** [comment]
Deployed to Staging

**Comment by szabozoltan69** [comment]
Delivered to Staging and to Production via a hotfix.
