### ISSUE TITLE
User for Kazakhstan sees DREF from Kyrgyzstan, but not from Kazakhstan in profile page

### ISSUE THREAD

**Issue by toffehoff** [IFRCGo/go-web-app#1212]
## Issue
A user (lena.kistaubayeva@redcrescent.kz) from Kazakhstan RC wants to submit an Ops Update for the DREF (MDRKZ013). The person is now a NS Staff member (according to GO). Still can't see the DREF.

## Steps to reproduce
Login as the account, go to the profile page > My Forms > DREF; There the KAZ DREFs are not shows.

![image](https://github.com/IFRCGo/go-web-app/assets/705634/544f46dc-784a-4d65-b696-04c6206237ea)

## Expected behaviour
Persons should see DREFs from her (his) NS. And not from other NSs

## Impact
Currently not that many people affected. However, the person affected cannot submit the needed Ops Updates.

## Severity
It is a blocking issue.

## Is there a workaround?
Have someone from regional PMER do the update....

**Comment by tovari** [comment]
Hi Henk, 
she should definitely see the MDRKAZ013 as she is added to that: 
![image](https://github.com/IFRCGo/go-web-app/assets/68283148/a66b67eb-b3da-4397-9b2f-e89661103449)
She is added to the Kyrgyzstan Epidemic DREF as well, so that is fine.

**Comment by toffehoff** [comment]
After added the account to the DREF problem has been solved. Will close ticket.
