### ISSUE TITLE
Replace Yarn with pnpm for build reliability

### ISSUE THREAD

**Issue by samshara** [IFRCGo/go-web-app#1351]
Currently, the build process often fails when using Yarn due to the following error:
```
Error: Extracting tar content of undefined failed
```

This issue causes builds to be unreliable and slows down development. After researching alternative package managers, `pnpm` has been identified as a more reliable and efficient option for our workflow.

#### Proposed Solution
1. Replace `yarn` with `pnpm` for managing dependencies and the build process.
2. Update project documentation to reflect the new setup.
3. Ensure CI/CD pipelines are updated to use pnpm instead of Yarn.

#### Benefits
- Improved build reliability.
- Potential for reduced build times.

**Comment by tnagorra** [comment]
We should be able to use `pnpm import` to import the lock file to pnpm.
Also, we can remove `post-install` package (it's already available on npm and pnpm)
