### ISSUE TITLE
Need to implement individual consideration for each component

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#1352]
## TODO
- [x] Follow the PER assessment guide document and add the individual description for each component. Link of the doc: https://drive.google.com/file/d/1WTaGu4-3E0nUvzbIMUjigmk9DgHz7frQ/view?usp=drive_link

**Comment by udaynwa** [comment]
@tovari , for this, are we implementing the individual consideration descriptions for each component following the [PER assessment guide-collapsible_EN (1).pdf](https://github.com/user-attachments/files/16928734/PER.assessment.guide-collapsible_EN.1.pdf) file? Currently, we have the same description for all the components.

For example: The descriptions for `DRM Strategy` would be the descriptions shown in the screenshot below: 
<img width="946" alt="Screenshot 2024-09-09 at 15 45 22" src="https://github.com/user-attachments/assets/e290f10a-61a6-456e-9a41-82876e938f65">

cc @samshara

**Comment by tovari** [comment]
@udaynwa, correct, that is the problem. We have the same descriptions for all components at the moment.

**Comment by udaynwa** [comment]
@tovari , just an FYI, we have also implemented the colors for the summary section (in Assessment form). 

![Image](https://github.com/user-attachments/assets/549c48b9-601f-43e6-af0c-23b77781fdec)
_Screenshot: Current state of Summary section in Assessment form_

cc @mariam-yu

**Comment by udaynwa** [comment]
@tovari , a quick question on the form sub-component for 14.M. Existing name in the database is "[CHEMICAL, BIOLOGICAL, RADIOLOGICAL AND NUCLEAR (CBRN) EMERGENCY PREPAREDNESS]" whereas in the [PER assessment guide-collapsible_EN (1).pdf](https://github.com/user-attachments/files/16928734/PER.assessment.guide-collapsible_EN.1.pdf) file, it is "TECHNOLOGICAL AND BIOLOGICAL (CBRN) HAZARDS PREPAREDNESS".  Do we rename it?

cc @Rup-Narayan-Rajbanshi

**Comment by tovari** [comment]
@udaynwa , @Rup-Narayan-Rajbanshi, 
The full one is the correct name, the long one
 
The other is like the resume, but it is more correct: CHEMICAL, BIOLOGICAL, RADIOLOGICAL AND NUCLEAR (CBRN) EMERGENCY PREPAREDNESS
