### ISSUE TITLE
Link to Surge Learning website from GO Resources page

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-web-app#1360]
I thought that there was a link to [surge learning website](https://surgelearning.ifrc.org/) from GO platform resources page - but I can't spot it now!

There is a link to the core competency framework on that site, from the [Catalogue of Surge Services overview page](https://go.ifrc.org/surge/catalogue/overview) - but not from Resources.

I would strongly suggest that [GO Resources page](https://go.ifrc.org/resources) Surge section has an additional link added:
![image](https://github.com/user-attachments/assets/b2bc1ef2-884c-49ce-a73c-b001ef64aaa0)
to  https://surgelearning.ifrc.org/

@anamariaescobar @esario can you please run this past surge team next time you're speaking with them, and check this is a good move to do?

Cheeers

**Comment by samshara** [comment]
@nanometrenat We have added additional link to surge pages based on this [ticket](https://github.com/IFRCGo/go-web-app/issues/1331).

This is on the [staging environment](https://github.com/IFRCGo/go-web-app/issues/1331). 

This will be on production after the next deployment.

**Comment by nanometrenat** [comment]
Great, thanks @samshara - that explains it - I thought I had seen it somewhere but it wasn't there.  Fixed pending release is the answer, I will close this ticket.  Cheers
