### ISSUE TITLE
Resources page - video updates

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#1370]
We would like to add one more video:
Global and local mapping on professional health services - https://youtu.be/Oyy_JboK9uY

The order of the videos should be:
- Monty
- 3w
- mapping
- user notifications
- using the 3w

Thanks!

**Comment by szabozoltan69** [comment]
Recent view – the 5th video thumbnail is visible only via scrolling:
![kép](https://github.com/user-attachments/assets/20d170c3-b248-4eb4-992a-aa2346afce1d)
