### ISSUE TITLE
New users - remove guest user limitation temporarily

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#1371]
AT the moment, new user accounts get limited as guest user accounts.
As we don't have implemented yet the registration process updates, users are not informed about this limitation, not able to request access either. Therefore, the limitation for new users should not be applied.

'Limit access to guest user permissions' should be 0.

Later when the UI will be updated, affected users will get the limited access by default.

#1079

**Comment by samshara** [comment]
@tovari, are we no longer assigning new users as guest users until the UI is updated?

**Comment by tovari** [comment]
> @tovari, are we no longer assigning new users as guest users until the UI is updated?

Correct. Only after the registration flow will be also updated.

**Comment by esario** [comment]
I think there's more urgency on this as I just noticed that every new user - even users from whitelisted domains - gets the "Limit access to guest user permissions" flag! So, e.g. an IFRC staff signing up can't see anything non-public.

**Comment by udaynwa** [comment]
Deployed to Staging and is ready for UAT. 

Following up on your comment @esario , we must manually visit the users and remove the guest user permissions for now. But now the newly registered users will not be tied up with guest user permissions.
