### ISSUE TITLE
[PROD] Update link to Legal status under country pages

### ISSUE THREAD

**Issue by esario** [IFRCGo/go-web-app#1394]
## Issue

The FedNet link to IFRC legal status under country pages -> National Society Overview -> Partners doesn't work after IFRC removed the FedNet page. The URL should be replaced with https://ifrcorg.sharepoint.com/sites/OurIFRCLegal/SitePages/Legal-Resources.aspx, and ideally, a disclaimer should be added to the link stating that it will only work for IFRC secretariat staff.

## Steps to reproduce

1. Navigate e.g. to https://go.ifrc.org/countries/181/ns-overview/partners and click the _legal status_ link.
2. Sign in to FedNet
3. Page is not found

**Comment by udaynwa** [comment]
@tovari , for the disclaimer, should we add a text `Disclaimer: The IFRC legal status will only work for the IFRC secretariat staff. ` below the links? 

cc @roshni73 @frozenhelium

**Comment by tovari** [comment]
@mariam-yu, can you suggest how we should show such a disclaimer? As a tooltip maybe as we have it on the maps?

@udaynwa, `Disclaimer: IFRC legal status document is shared only with IFRC staff.`

**Comment by mariam-yu** [comment]
@tovari @udaynwa yes tooltip icon would be best to the right of the text. Wondering if we need the word "disclaimer". Maybe the text to clarify that it won't work for others. Maybe something like "This link will only be accessible to IFRC staff."
