### ISSUE TITLE
Country pages - Context and Structure - FDRS data incorrectly displayed

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#1396]
National Society Indicators are currently not displaying the correct values on the GO country pages.

Example: Belize https://go.ifrc.org/countries/31/ns-overview/context-and-structure

![image](https://github.com/user-attachments/assets/b18336f1-b027-4dd1-92ee-de51d083ba1a)

**Branches**: It currently displays _KPI_noLocalUnits_, but it should display _KPI_noBranches_ (we added the number of branches as of this year [2023])
**Youth (6-29 yrs)**: Should be 20? (_KPI_PeopleVol_Tot_age_18_29_ + _KPI_Pstaff_Tot_age_18_29_ = 18 +2 = 20 )

I think generally something goes wrong with the disaggregation’s here: There is no 13-17, nor 70-79 reported.

![image](https://github.com/user-attachments/assets/53d520dd-c6ce-4570-acc3-3bab30f8bdbe)

![image](https://github.com/user-attachments/assets/f3c4a1aa-7b9b-42a6-8c10-7b5ac4e019ae)

Source: All this data is from 2022, not 2023.

**Comment by susilnem** [comment]
Hey @tovari,

1. For branches, we're currently using `KPI_noLocalUnits` since `KPI_noBranches` has not yet been updated in the FDRS APIs.

2. For the Youth category (ages 6-29), we are using following formula:

```
Youth (6-29 years) = KPI_PeopleVol_Tot_age_6_12 + KPI_PeopleVol_Tot_age_13_17 + KPI_PeopleVol_Tot_age_18_29 + KPI_PStaff_Tot_age_18_29
```
Should we make any change to the calculation?

3. Regarding volunteer disaggregation, we're utilizing the available data from FDRS, and for any missing data, we're relying on figures from previous years. If we show the data from a specific year or latest year, there are chances that the data might not be available. And the chart might be null. 

For the year, we are currently showing the latest year from available data. 

Should we make any changes to the current implementations? 

cc @samshara @udaynwa @frozenhelium @thenav56

**Comment by tovari** [comment]
hey @susilnem,

1.	For branches, we're currently using KPI_noLocalUnits since KPI_noBranches has not yet been updated in the FDRS APIs. 

So, it has been just updated (KPI_noBranches) in the Data2 FDRS API (note that we only started collecting this information for 2023)

2.	For the Youth category (ages 6-29), we are using following formula:
Youth (6-29 years) = KPI_PeopleVol_Tot_age_6_12 + KPI_PeopleVol_Tot_age_13_17 + KPI_PeopleVol_Tot_age_18_29 + KPI_PStaff_Tot_age_18_29
Should we make any change to the calculation?

The logic of this calculation is correct! But from some digging, it looks like you are mixing and matching disaggregation from different years. I would recommend you stick to 2022 only if that is the latest year available. For example for Belize, It looks like “KPI_PeopleVol_Tot_age_13_17” is from 2021, the other age groups are from 2022,

3.	Regarding volunteer disaggregation, we're utilizing the available data from FDRS, and for any missing data, we're relying on figures from previous years. If we show the data from a specific year or latest year, there are chances that the data might not be available. And the chart might be null.
It seems that GO is taking for Belize, volunteers aging 70-79 from 2019 (2), volunteers aging 13-18 from 2021 (5), and the Total number of volunteers from 2022 (86), showing the data source is FDRS 2023.
Recommend you stick to values of only 1 year for all (FDRS) numbers displayed on the country page
For the year, we are currently showing the latest year from available data.
Yes this makes sense! 
Recommend you change the source_year_value to the latest year, so 2022 if it is 2022 data, 2023 if it is 2023 data, et cetera.

**Comment by tovari** [comment]
@samshara, regarding the incomplete data from the latest available year: we can take data from the latest year, where the missing data is available. We need to indicate the year at the source info (e.g. Belize RC on FDRS, 2022, 2023, 2024) in such case.
We should not fill missing disaggregated data though (e.g. gender/age group data from different years - all these should be taken from the same year).

**Comment by samshara** [comment]
> [@samshara](https://github.com/samshara), regarding the incomplete data from the latest available year: we can take data from the latest year, where the missing data is available. We need to indicate the year at the source info (e.g. Belize RC on FDRS, 2022, 2023, 2024) in such case. We should not fill missing disaggregated data though (e.g. gender/age group data from different years - all these should be taken from the same year).

@tovari we have created two tickets to address this issue

- https://github.com/IFRCGo/go-api/issues/2285
- https://github.com/IFRCGo/go-web-app/issues/1433
