### ISSUE TITLE
DREF import template: Update the error popup to include an email link to the DREF team

### ISSUE THREAD

**Issue by samshara** [IFRCGo/go-web-app#1444]
Maybe we need to update the text and error message too. @frozenhelium

**Comment by frozenhelium** [comment]
@tovari @marcovvu1 could you provide an email address which will be added to the error message for the DREF import (in case it fails)

**Comment by samshara** [comment]
As per discussion with @tovari we add the following text instead
`Please contact your DREF focal point in your region.`
