### ISSUE TITLE
Surge CoS - Health updates

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#1448]
Could you please support us with updating the Health section of the Catalogue of Surge Services. 
•	Under [Community Case Management of Malnutrition (CCMC)](https://go.ifrc.org/surge/catalogue/health/community-management-malnutrition), update the different sections with the revised text provided in   Column B
•	Under [Community Based Surveillance (CBS)](https://go.ifrc.org/surge/catalogue/health/community-based-surveillance), update the different sections with the revised text provided in   Column C
•	Under [Safe and Dignified Burials](https://go.ifrc.org/surge/catalogue/health/safe-dignified-burials), update the different sections with the revised text provided in   Column D

Additionally, under the [Services section](https://go.ifrc.org/surge/catalogue/health), could you create an additional box for Public Health / Infection Prevention and Control (IPC), and then create the different sections (using same template as the above) with the content from   Column E.

In case of any questions, Bronwyn Nichol can help.

[Copy of Catalogue of services _ PH ERU_2024 - Copy.xlsx](https://github.com/user-attachments/files/17619550/Copy.of.Catalogue.of.services._.PH.ERU_2024.-.Copy.xlsx)

**Comment by szabozoltan69** [comment]
The attached .xlsx file has a "Community Case Management of Cholera (CCMC)" column also, which is not mentioned in the ticket. Should it be used?

I received the answer in email:
They meant to put community case management of cholera, the acronym (CCMC) is correct!
We’d actually like to remove anything about the "malnutrition ERU" from the catalog for the moment.

**Comment by samshara** [comment]
@tovari @szabozoltan69 there is `DEPLOYABLE` text in the capacity row for each of the columns. Should we add this too?

**Comment by szabozoltan69** [comment]
Correspondance with Bronwyn:

_Does "(Not yet deployable)" mean (at Burials) that we should not deploy it to production website?_
 
Under the capacity section could you put the text “under development”.  This is what we curtly have for malnutrition which is not yet ready to deploy.
