### ISSUE TITLE
Bullet points in Flash Update

### ISSUE THREAD

**Issue by toffehoff** [IFRCGo/go-web-app#1481]
**Is your feature request related to a problem? Please describe.**
*When creating a Flash Update, I want to be able to use bullet points in the Situational Overview*

**Describe the solution you'd like**
*Add the bullet points icon in the edit-bar*

**Describe alternatives you've considered**
*I can use an asterisk or a dash, but this will not look that well with the alignment...*

**Additional context**
![Image](https://github.com/user-attachments/assets/7264d8dc-1c23-4294-8ba9-a9924e8643b4)

**Comment by szabozoltan69** [comment]
This (bullet point) really should be possible.
On Admin page it is allowed, and could be allowed on frontend also.
