### ISSUE TITLE
Hide Local unit contact details on the list view for logged in users

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#1485]
There are data privacy concerns therefore I ask to hide Focal person _name, phone number and email_ from the Local unit List View.

https://go.ifrc.org/countries/116/ns-overview/context-and-structure

Could be visible though for those, who have access to the Local Unit Form.

**Comment by samshara** [comment]
@tovari Should this be hidden for all logged-in users, or should it remain visible to specific users based on their permissions?

**Comment by tovari** [comment]
@samshara, who has editing access currently? I couldn't find out based on the permissions. 
Best would be to show this for users with editing permission.

**Comment by samshara** [comment]
@tovari Currently, edit access is restricted in the production environment. 
In the staging environment, edit access is available for **CountryAdmin** and **SuperUser** roles. 
Per [issue #1415](https://github.com/IFRCGo/go-web-app/issues/1415), the workflow will soon include **RegionAdmin** as well.

We will be hiding the details for other users.
