### ISSUE TITLE
Add .nvmrc

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-web-app#286]
Can we add a .nvmrc so its clear what version of node is required?

cc @tnagorra

**Comment by tnagorra** [comment]
We do currently have a Dockerfile that locks the node version we are using.
https://github.com/IFRCGo/go-web-app/blob/develop/Dockerfile

We can add a .nvmrc for those running the application without docker.

**Comment by batpad** [comment]
As long as the node version is pinned somewhere, that's fine, I just instinctively tend to look for a .nvmrc - sorry for filing before checking.
