### ISSUE TITLE
DREF regional permissions not working for some users

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-web-app#290]
Some users have reported that permissions for DREF are not working as expected, this user (Melina Miele) can see DREFs from Africa, when she doesn’t even has Regional Admin rights, she should only be able to see DREFs she has been added to. I tested and can't reproduce the problem.
![image](https://github.com/IFRCGo/go-web-app/assets/69478743/d69bb1e9-323b-4580-8539-f828d106223e)
![image](https://github.com/IFRCGo/go-web-app/assets/69478743/44119148-f114-43c2-ba0e-d58701a796b6)

@tovari @udaynwa

**Comment by frozenhelium** [comment]
@anamariaescobar This issue should be fixed now!

CC: @tovari @udaynwa @nnjemie

**Comment by anamariaescobar** [comment]
Checked in staging, also with the users that were experiencing the issue and all is working fine now! Thanks for the fix!
