### ISSUE TITLE
Add COP28 Blog Report

### ISSUE THREAD

**Issue by hamishwp** [IFRCGo/go-web-app#292]
Hi team,

Please could we add a PDF, exported from this Google Doc: 
https://docs.google.com/document/d/113o0M98OUy7DVBPPGkIyPivs8iNCg0vqPhPtohu7E20/edit?usp=sharing
to the GO Resources page? Anywhere you think best, as it's only important that the report is linked somehow to IFRC and GO to gain credibility.

This report is to support a blog post that IFRC are putting forward for COP28. Luke approved for me today that we stick the document up there. Ideally, the document should be live as soon as possible, as they're planning on publishing the blog post soon, and this should be live before then. Apologies for adding more work on your plate! 

@szabozoltan69

Many thanks,
Hamish

**Comment by szabozoltan69** [comment]
@LukeCaley – what should be the link text, and in which section would it be the most appropriate?
@mariam-yu – any design considerations?
Maybe here as "COP28 Report"?
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/dd392773-bc50-4a14-81ad-955f2f111f64)

**Comment by szabozoltan69** [comment]
The planned URL is this:
https://prddsgofilestorage.blob.core.windows.net/api/documents/cop28/COP28.pdf
If this location is not appropriate (or you know a better one), let me know. (This is the "General Document" storage on GO admin.)

**Comment by hamishwp** [comment]
Thank you, Zoltan! Please could we name it "_COP28 'All About That Base' Report_". Also, do you think it might be possible to have an URL leading with go.ifrc.org? Or are all resources hosted directly on the storage server for GO?

**Comment by szabozoltan69** [comment]
Well, basically we don't keep any .pdf files on go.ifrc.org, as far as I know.
All the surge documents are on SharePoint, and some of them are on the storage server for GO ( = prdds**go**filestorage...).
In this case we can make an exception if really important. Or maybe we can create an URL on go.ifrc.org, which leads to a page containing the link.

**Comment by LukeCaley** [comment]
I think directing users to the GO resources page and letting them find it among the available links is good enough, thanks @szabozoltan69

**Comment by szabozoltan69** [comment]
So this will be it:  https://go.ifrc.org/resources
![image](https://github.com/IFRCGo/go-web-app/assets/6050643/e53aad95-720a-4b4d-9cea-c404190852d9)
– leading to https://prddsgofilestorage.blob.core.windows.net/api/documents/cop28/COP28.pdf

**Comment by szabozoltan69** [comment]
The Staging release was done ( https://go-stage.ifrc.org/resources – ctrl+F5 to be sure of the reload), now the Prod is coming...

**Comment by szabozoltan69** [comment]
Deployed to Prod nicely. https://go.ifrc.org/resources (CTRL+F5)

**Comment by hamishwp** [comment]
Thank you Zoltan and Luke!
