### ISSUE TITLE
Imminent DREF export - missing field

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#310]
Section “Event Details”, there is a field called “Approximate date of impact” doesn't show up on the export.

**Comment by frozenhelium** [comment]
@tovari @anamariaescobar Previously, we only had this is DREF Application export and it should remain that way, right?

Or, we're adding it to Ops. Update and Final Report as well?

**Comment by frozenhelium** [comment]
@tovari @anamariaescobar This is fixed and deployed to prod in v7.0.13

**Comment by anamariaescobar** [comment]
@marcovvu1 would you mind checking this one in production??

**Comment by marcovvu1** [comment]
Confirmed, is appearing now
