### ISSUE TITLE
Sentry  413 - Request Entity Too Large issue

### ISSUE THREAD

**Issue by thenav56** [IFRCGo/go-web-app#32]
## Issue
Sentry tries to send most of the data to the server to provide additional context related to errors. Right now sentry is also sending the API response which sometimes can cause 413 errors. We should have a check to make sure we scrub the data if it hits the limitation.

## How to fix
We can use sentry SDK to clean up data before sending using the `beforeSend` hook.
https://docs.sentry.io/platforms/javascript/guides/react/data-management/sensitive-data/#scrubbing-data

## Context
There was an error on the DREF page which is not showing in sentry. https://go-stage.ifrc.org/account#my-dref-applications. It is being rejected by a sentry with the error `envelope exceeded size limits (https://develop.sentry.dev/sdk/envelopes/#size-limits)`
![2023-07-04-150451](https://github.com/IFRCGo/go-web-app/assets/7059255/ec70a69a-7f1c-46ac-882b-8f916a11b539)
![2023-07-04-150445](https://github.com/IFRCGo/go-web-app/assets/7059255/1f40f3f2-11d3-41fe-b8c1-5012a678e41a)

## Additional info
We can see how many sentry events are rejected from the stats page in sentry.

https://sentry.northeurope.cloudapp.azure.com/organizations/ifrc-go/stats/
![2023-07-04-150627](https://github.com/IFRCGo/go-web-app/assets/7059255/d3097a38-39d8-4a7a-b90e-61b4bc2235f8)
![2023-07-04-150733](https://github.com/IFRCGo/go-web-app/assets/7059255/760b9d2e-fc5c-42b5-860a-13d152a13b2f)

**Comment by frozenhelium** [comment]
@thenav56 this issue is not longer applicable since we're no longer using Redux. Are we still getting errors related to this? If not, lets close this issue.

**Comment by thenav56** [comment]
This seems to be fixed.

![image](https://github.com/IFRCGo/go-web-app/assets/7059255/4fae0bb4-275d-4e83-8e29-5f0fe0962980)
