### ISSUE TITLE
National Society Overview > Context and Structure

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#334]
# NS Local Units
### Country where data is available 
- United Kingdom: https://go-web-ifrc.dev.datafriendlyspace.org/countries/3/ns-overview/context-and-structure
- Gautemala: https://go-web-ifrc.dev.datafriendlyspace.org/countries/76/ns-overview/context-and-structure
- United States: https://go-web-ifrc.dev.datafriendlyspace.org/countries/4/ns-overview/context-and-structure
- Costa Rica : https://go-web-ifrc.dev.datafriendlyspace.org/countries/51/ns-overview/context-and-structure
# NS Directory
### Figma link
- https://www.figma.com/file/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?type=design&node-id=82-32028&mode=design&t=n8Be8fXTYRRoXjk3-4
### Google Colab link
- https://colab.research.google.com/drive/13XdiBTHqM3Z7L18kaZlbGevR5Ulft6y8?authuser=0#scrollTo=xZ3C00wW15rD
#### Available data
- First Name
- Last Name
- Country
- CON Title
#### Unavailable data
- None
#### Remarks
- All the required data for this section is available

# Key Documents
### Figma link
- https://www.figma.com/file/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?type=design&node-id=82-32276&mode=design&t=n8Be8fXTYRRoXjk3-4
### Google Colab link
- https://colab.research.google.com/drive/1cwlmvs91Yz8zWxqrk07btxdGCa8oR6Xf#scrollTo=Dg_JwpifPHcH

### Country where data is available 
https://go-web-ifrc.dev.datafriendlyspace.org/countries/3/ns-overview/context-and-structure
#### Available data
- Name
- Language
- url
- thumbnail
- year
- Document Type
- Year text
#### Unavailable data
- None
#### Remarks
- All the required data for this section is available

# National Society Indicators
### Figma link
- https://www.figma.com/file/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?type=design&node-id=82-31956&mode=design&t=n8Be8fXTYRRoXjk3-4
### Google Colab links
- https://colab.research.google.com/drive/1DhS_lV9Kii2Tfff9xnmFAMq7bySP4w4a?usp=sharing
- https://drive.google.com/file/d/14aJPluXTJvmSjAahofNwDh-hS0ngcPD9/view?usp=drive_link
#### Available data
- Income (CHF)
- Expenditure (CHF)
- Staff 
- Volunteers
- Trained in first aid
- Date Founded
- Branches
- Youth 6-29 years
#### Unavailable data
- Multipurpose Cash*
- Sectorial Cash* 
#### Remarks
- For `Youth 6-29 years`, data for 18 and above is available
- `Multipurpose Cash` and `Sectorial Cash`
  - We have used the `Consolidation` worksheet from [CC Consolidation](https://docs.google.com/spreadsheets/d/1M8iqMyfy1cAfmjihP560SJNH3HZVmYoRZP1HKcBOG4U/edit#gid=383426070) sheet listed in the Figma. 
  - We have multiple rows under `multi_purpose_cash`. Are we totaling them and displaying the sum?
  - We could not find any related data for `Sectorial Cash` in the sheet. Are we totaling the `Project Objective (Sector)` (except `multi_purpose_cash`) for `Sectorial Cash`?
  - For `People Reached`, are we displaying the sum of the `Total beneficiary` column? 
  - For `CHF distributed`, are we displaying the sum of the `Total cash expended (CHF) calculated via Exchange rate sheet` column?

# NSD Initiatives
### Figma link
- https://www.figma.com/file/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?type=design&node-id=82-32253&mode=design&t=n8Be8fXTYRRoXjk3-4
### Google Colab link
- https://colab.research.google.com/drive/1NLfwu1B1XovbE-i76AYaTg8ojDHKqeSS#scrollTo=nhfvDSjYYZIA

### Country where data are available
https://go-web-ifrc.dev.datafriendlyspace.org/countries/21/ns-overview/context-and-structure
https://go-web-ifrc.dev.datafriendlyspace.org/countries/121/ns-overview/context-and-structure

#### Available data
- Id
- NationalSociety
- Year
- Fund
- InitiativeTitle
- Categories
- AllocationInCHF
- FundingPeriodInMonths
#### Unavailable data
- Funding type
#### Remarks
- The data for `Funding type` is not available. 
- We have called 3 APIs for different fund names, so it might take a bit of time to load 

# Main source of income (Last 3 years)
### Figma link
- https://www.figma.com/file/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?type=design&node-id=82-32147&mode=design&t=n8Be8fXTYRRoXjk3-4
### Google Colab link
- https://colab.research.google.com/drive/1E8xhhGagwbpCmMdgsQ0E5B7GwkkqN2sR#scrollTo=WKfdTKO7N3_f
#### Available data
- Income (CHF)
- Year
- Organizations
#### Unavailable data
- None
#### Remarks
- The design says `last 3 years` but in the Colab link, we have pulled all the data. Can be filtered out as per need
- The design only shows 3 organizations, but multiple organizations are available in the external source. This too can be filtered out
- For the cases where the income data is unavailable or 0, FDRS is showing them as `n/a`

**Comment by samshara** [comment]
@tovari, there are a lot of indicators (1843) for the `main sources of income.` Do you have documentation for these indicators? If so, we need it, as well as the list of indicators to use. I think we need to involve Alex and Mariam as well.

**Comment by udaynwa** [comment]
@tovari , we have added a few questions related to `Multipurpose Cash and Sectorial Cash` in the Remarks of `National Society Indicators` section. Please go through them. 

cc @mariam-yu

**Comment by udaynwa** [comment]
@tovari , we have updated the `Unavailable data` and `Remarks` sections of `NSD Initiatives`. The data for `Funding type` is not available

**Comment by tovari** [comment]
NS Indicators
#### Remarks
- For `Youth 6-29 years`, data for 18 and above is available:
This group consists of 3 age groups: 6-12, 13-17 and 18-29
KPI_PeopleVol_Tot_age_6_12
KPI_PeopleVol_Tot_age_13_17
KPI_PeopleVol_Tot_age_18_29

**Comment by tovari** [comment]
> @tovari, there are a lot of indicators (1843) for the `main sources of income.` Do you have documentation for these indicators? If so, we need it, as well as the list of indicators to use. I think we need to involve Alex and Mariam as well.

More information on indicators can be found here in the user guide: https://data.ifrc.org/FDRS/resources

**Comment by tovari** [comment]
NSD Initiatives:

Funding type can be
- ESL: Empress Shôken Fund
- NSIA : National Society Investment Alliance 
- CBF: Capacity Building Fund

**Comment by tovari** [comment]
#### Remarks

_- `Multipurpose Cash` and `Sectorial Cash`
  - We have used the `Consolidation` worksheet from [CC Consolidation](https://docs.google.com/spreadsheets/d/1M8iqMyfy1cAfmjihP560SJNH3HZVmYoRZP1HKcBOG4U/edit#gid=383426070) sheet listed in the Figma. 
  - We have multiple rows under `multi_purpose_cash`. Are we totaling them and displaying the sum?
  - We could not find any related data for `Sectorial Cash` in the sheet. Are we totaling the `Project Objective (Sector)` (except `multi_purpose_cash`) for `Sectorial Cash`?
  - For `People Reached`, are we displaying the sum of the `Total beneficiary` column? 
  - For `CHF distributed`, are we displaying the sum of the `Total cash expended (CHF) calculated via Exchange rate sheet` column?_

**We agreed with the source owner that we will create a new worksheet for GO, which will contain the required values for each country, so those can be taken and no calculation will be required on the GO side.**

**Comment by samshara** [comment]
> th the source owner that we will create a new worksheet for GO, which will contain the required values for each country, so those can be taken and no calculation will be required on the GO side.

Thanks @tovari . That would make it easier and cleaner to implement as well.

**Comment by udaynwa** [comment]
@tovari @AlexxxH , here is the list of all the available indicators. We need the list of only required indicators for `Main source of income (last 3 years)` section.
[List of indicators.csv](https://github.com/IFRCGo/go-web-app/files/13917199/List.of.indicators.csv)

cc @samshara

**Comment by AlexxxH** [comment]
Here is a dataset mapping the IFRC disaster law country codes "node" to the country names and ISO codes
https://disasterlaw.ifrc.org/where-we-work

[IFRC Disaster Law countries.csv](https://github.com/IFRCGo/go-web-app/files/13918090/IFRC.Disaster.Law.countries.csv)

**Comment by AlexxxH** [comment]
@udaynwa The income source indicators are those starting "Income from...", I've highlighted them in the doc below.
I will check with Mariam if we should show all of them or only the top few

[List.of.indicators.xlsx](https://github.com/IFRCGo/go-web-app/files/13918191/List.of.indicators.xlsx)

**Comment by AlexxxH** [comment]
Here is a list of NSs and the years they were founded (this data is static):

[NS founded dates.xlsx](https://github.com/IFRCGo/go-web-app/files/13920515/NS.founded.dates.xlsx)

**Comment by AlexxxH** [comment]
Hi, the income sources graphs are updated in the wireframes now (shoing the total income on the left chart, and all income sources in the pie chart)
