### ISSUE TITLE
National Society Overview > Capacity

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#335]
# Organisational capacity
### Figma link
- https://www.figma.com/file/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?type=design&node-id=82-29436&mode=design&t=n8Be8fXTYRRoXjk3-4
### Google Colab link
- https://drive.google.com/file/d/1EjVYA3YAn0tg3cQgadV5F2rb-HEuGZzW/view?usp=drive_link

### Country where data is available
https://go-web-ifrc.dev.datafriendlyspace.org/countries/27/ns-overview/capacity
#### Available data
- There are 4 sub-sections in the designs. Data is partially available only for few countries for each section
- For `Leadership Capacity`, there are 40 records. Out of them, descriptions are available for only 8 of them
- For `Volunteer Capacity`, there are 38 records. Out of them, descriptions are available for only 30 of them
- For `Youth Capacity`, there are 38 records. Out of them, descriptions are available for only 37 of them
- For `Financial Capacity`, there are 38 records. Out of them, descriptions are available for only 12 of them
#### Unavailable data
- Partial availability
#### Remarks
- Partial availability of data
- Excel file is being used for the analysis. So, you need to download the file from the link: https://ifrcorg.sharepoint.com/:x:/s/APPSK/EVCVrmWRua5Aj_VAGYYMwFkBpGb2-yocVt2_xblabluP-Q?email=mariam%40yllwu.com&e=xmyNea . Then you need to upload the file in the Google Colab and rename it to `capacity.xlsx`

# Capacity strengthening and development process
### Figma link
- https://www.figma.com/file/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?type=design&node-id=82-29157&mode=design&t=2hWWm5GMkFZShuID-0
### Google Colab link
- https://drive.google.com/file/d/1lWcTojQ1qtKYMVYnn57woDmCJegDL7y9/view?usp=drive_link
### Country where data is available
https://go-web-ifrc.dev.datafriendlyspace.org/countries/27/ns-overview/capacity
#### Available data
- In, `OCAC Assessment`,
  - YearOfAssessment
  - SubmissionDate
- In, `BOCA Assessment`, `BranchName` is available
#### Unavailable data
- In, `OCAC Assessment` and `BOCA Assessment`,
  - `Last Updated`
#### Remarks
- We have `SubmissionDate`. Are we assuming `SubmissionDate` as `Last Updated` date?
- We do not have `month` related date. Do we extract it from the `SubmissionDate`?
- Where are we directing users to after clicking on `View details` button?
- For `BOCA Assessment`, we do not have `Local Units/Branches` data, but we do have the branch names. So, do we count them as `Local Units/Branches` numbers?

**Comment by tovari** [comment]
### Organisational capacity



### Capacity strengthening and development process

#### Remarks
- We have `SubmissionDate`. Are we assuming `SubmissionDate` as `Last Updated` date?
Correct
- We do not have `month` related date. Do we extract it from the `SubmissionDate`?
Yes
- Where are we directing users to after clicking on `View details` button?
@mariam-yu 
- For `BOCA Assessment`, we do not have `Local Units/Branches` data, but we do have the branch names. So, do we count them as `Local Units/Branches` numbers?
Correct

**Comment by mariam-yu** [comment]
@udaynwa for View Details, they should go to respective OCAC/BOCA dashboards (user would need to login though): https://data.ifrc.org/ Not sure from here though.

**Comment by tovari** [comment]
> @udaynwa for View Details, they should go to respective OCAC/BOCA dashboards (user would need to login though): https://data.ifrc.org/ Not sure from here though.

https://data.ifrc.org/en/ocac
https://data.ifrc.org/en/boca

**Comment by udaynwa** [comment]
@tovari , we have multiple assessments for OCAC and BOCA. Are we showing all the assessments or only the latest one for both? The assessments have individual links. Do we show these links or the links you have shared in the comment above?

**Comment by mariam-yu** [comment]
@udaynwa How many would it be per country if we were to show all? In theory it would be good to show all, with time to add filters. We can also show the most recent with a View All button like the other modules.

**Comment by udaynwa** [comment]
@tovari , can you please verify if we are using the correct links? 

`View Details` button of BOCA assessment: https://data.ifrc.org/en/BOCA/Form?donCode=DBD001
`View Details` button of OCAC assessment:https://data.ifrc.org/en/OCAC/Form?donCode=DBD001&version=%7C2014%7C

cc @samshara

**Comment by AlexxxH** [comment]
@tovari @udaynwa Please could you **remove** the "Organisational capacity" information on this page? This data is currently under review so not ready to include yet, best to include in the next version. Thanks!
