### ISSUE TITLE
Country Profile > Overview

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#336]
# Country Key Indicators
### Figma link
- https://www.figma.com/file/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?type=design&node-id=82-26948&mode=design
### Google Colab link
- https://drive.google.com/file/d/1N6mamCNH0x8yV30z7_0jZyLWtPHPcQg9/view?usp=drive_link
#### Available data
- Population
- Population over 65
- Urban pop
- GDP
- GNI/CAPITA
- Poverty (% POP)
- Life expectancy
- Literacy
- Gender inequality index (GII)
- Population under 18
#### Unavailable data
- Number of people under poverty rate
- Number of people in disaster-prone zones
#### Remarks
- `Population under 18` not found but `Population ages 0-14` is found. Can we consider them the same?
Link: https://data.worldbank.org/indicator/SP.POP.0014.TO.ZS?view=chart
- Is `Number of people under poverty rate` is same as the indicator `Poverty headcount ratio at national poverty lines (% of population)`? Please confirm. Link: https://data.worldbank.org/indicator/SI.POV.NAHC?view=chart

# Seasonal Calendar
### Figma link
- https://www.figma.com/file/uRgMamNHRi5KhhroYDwuxN/%5BOLD%5D-IFRC-GO---Wireframes?type=design&node-id=20331-10792&mode=design&t=Ku18qN8MYgXiKCzI-4
### Google Colab link
- https://drive.google.com/file/d/1MatVjc7wfpCny0OdlUgDUFffzW6nhB_y/view?usp=drive_link
#### Available data
- Country 
- Months 
- Event 
- Event_type 
- Label
#### Unavailable data
- None
#### Remarks
- All the necessary data are available

# Population Map (including `key climate events` and `key dates`)
### Figma link
- https://www.figma.com/file/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?type=design&node-id=82-26948&mode=design&t=n8Be8fXTYRRoXjk3-4
### Google Colab link
- https://drive.google.com/file/d/1QkqMjDdlBoLATQcFFjCHji4DdX1abOhZ/view?usp=drive_link
#### Available data
- None
#### Unavailable data
- Population Map
- Key Climate Event
- Key Dates
#### Remarks
- Data source used for `Population Map` : [World Bank](https://databank.worldbank.org/reports.aspx?source=subnational-population)
- No data available for `Key Climate Events` and `Key Dates`

**Comment by tovari** [comment]
Gender Inequity Index source api:
Endpoint with country, year and indicator filters:
curl -X 'GET' \
  'https://api.hdrdata.org/CountryIndicators/filter?country=hun&year=2021&indicator=gii' \
  -H 'accept: */*'
API documentation page: [https://api.hdrdata.org/swagger](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.hdrdata.org%2Fswagger&data=05%7C01%7Cadmir.jahic%40undp.org%7C849f3ec1f6dd431483c308dbd40834c1%7Cb3e5db5e2944483799f57488ace54319%7C0%7C0%7C638336903923225028%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=996uYGxfyQ1%2FGGC7T9sTnJ6q%2FfuKGSD%2BjBFdGNkpY6g%3D&reserved=0)

**Comment by AlexxxH** [comment]
UNICEF has data on "Population under 18". 
At the following link, select "Dataflow" = "DM - Demography" and "Indicator" = "Population under age 18 [DM_POP_U18]" https://sdmx.data.unicef.org/webservice/data.html 

E.g. for Afghanistan: https://sdmx.data.unicef.org/ws/public/sdmxapi/rest/data/UNICEF,DM,1.0/AFG.DM_POP_U18._T._T.?format=sdmx-json
The last value in "observations" corresponds to the last value in "values", and observations are in thousands. I.e. the total population under 18 in Afghanistan was 3533869 in 1950, and 21087410 in 2023 (this is visualised here https://data.unicef.org/how-many/how-many-children-under-18-are-there-in-afghanistan/ )

**Comment by AlexxxH** [comment]
For "Number of people under poverty rate", it looks like there are a few options from WorldBank, e.g. [Poverty headcount ratio at $2.15 a day](https://data.worldbank.org/indicator/SI.POV.DDAY), and [Poverty headcount ratio at national poverty lines](https://data.worldbank.org/indicator/SI.POV.NAHC). 

What do you think, @tovari ? Is there one that is generally used on GO?

**Comment by AlexxxH** [comment]
The seasonal calendar is back in the wires (data source here: https://api.acaps.org/api/v1/seasonal-events-calendar/seasonal-calendar/ )

**Comment by tovari** [comment]
We don't use either of them at the moment. 
My opinion is that national poverty levels are more relevant than a global poverty threshold. 

> For "Number of people under poverty rate", it looks like there are a few options from WorldBank, e.g. [Poverty headcount ratio at $2.15 a day](https://data.worldbank.org/indicator/SI.POV.DDAY), and [Poverty headcount ratio at national poverty lines](https://data.worldbank.org/indicator/SI.POV.NAHC).
> 
> What do you think, @tovari ? Is there one that is generally used on GO?

**Comment by tovari** [comment]
@davidmuchatiza, would you mind sharing here the population data per admin1? the version you have matched to the GO admin1 areas. Thanks!

**Comment by davidmuchatiza** [comment]
[Here](https://ifrcorg.sharepoint.com/:x:/r/sites/GOIVfordeveloperteam/Shared%20Documents/General/Geospatial/Admin%20Layers/Population%20Data/Population%20GO%20Admin1%20Matched.xlsx?d=wd860e675e3e546939b0ecfdcfd052090&csf=1&web=1&e=3MmgcA) is the population dataset matched to GO Admin1 using the Name field.

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-web-app/issues/1281
