### ISSUE TITLE
Country Profile > Supporting Partners

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#337]
# IFRC Presence and ICRC Presence 
### Figma link
- IFRC Presence: https://www.figma.com/file/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?type=design&node-id=82-28752&mode=design&t=n8Be8fXTYRRoXjk3-4
- ICRC Presence: https://www.figma.com/file/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?type=design&node-id=82-28759&mode=design&t=n8Be8fXTYRRoXjk3-4
### Google Colab link
- https://drive.google.com/file/d/1QkqMjDdlBoLATQcFFjCHji4DdX1abOhZ/view?usp=drive_link

### Country where data are available
https://go-web-ifrc.dev.datafriendlyspace.org/countries/27/profile/supporting-partners
#### Available data
- IFRC Presence
  - Name
  - Designation
  - IFRC Legal status link
  - IFRC disaster law link
- ICRC Presence
  - Key Operations links for available countries (24 countries)
#### Unavailable data
- IFRC Presence
  - Contact Information
  - Email ID
- ICRC Presence 
  - None
#### Remarks
- For `IFRC Presence`, the data is pulled from the XML file attached in the Figma 

# Contacts
### Figma link
- https://www.figma.com/file/myeW85ibN5p2SlnXcEpxFD/IFRC-GO---UI-Current---1?type=design&node-id=15913-238285&mode=design&t=Y94ci9gob6cJakvd-4
### Google Colab link
- https://colab.research.google.com/drive/13XdiBTHqM3Z7L18kaZlbGevR5Ulft6y8?authuser=0#scrollTo=xZ3C00wW15rD
### Country where data is available
- https://go-web-ifrc.dev.datafriendlyspace.org/countries/14/profile/supporting-partners
#### Available data
- IFRC 
  - First Name
  - Last Name
  - Country
  - CON Title
  - Email ID
- International Partners
#### Unavailable data
- None
#### Remarks
- Where are we pulling data from for `International Partners`?

**Comment by udaynwa** [comment]
@mariam-yu @tovari , `Contacts` section added here. Comment related to source for `International Partners` also added in the Figma : https://www.figma.com/file/myeW85ibN5p2SlnXcEpxFD?node-id=15913:238042&mode=design#652382061

cc @frozenhelium

**Comment by udaynwa** [comment]
@tovari @szabozoltan69 , there are delegation fields in Local Units. Can we use them for `IFRC Presence`? 

cc @samshara

**Comment by udaynwa** [comment]
@barshathakuri , 

- [x] Verify the API with the Excel file mapping the IFRC disaster law country codes "node" to the country names and ISO codes

**Comment by tovari** [comment]
Yes, please use the delegation-office endpoint for this.

> @tovari @szabozoltan69 , there are delegation fields in Local Units. Can we use them for `IFRC Presence`?
> 
> cc @samshara

**Comment by tovari** [comment]
IFRC Presence data don't show up on any of the country pages. E.g.:
https://go.ifrc.org/countries/132/ns-overview/partners

from 
_https://goadmin.ifrc.org/api/v2/delegation-office/_
        {
            "name": "Americas Regional Office",
            "city": "Panama City",
            "address": "Av. Jacinto Palacios Cobos Edificio 221, Panamá, Panama",
            "postcode": "",
            "location": {
                "type": "Point",
                "coordinates": [
                    -79.58557096,
                    9.005326423
                ]
            },
            "society_url": "https://www.cruzroja.org.pa/",
            "url_ifrc": "https://www.ifrc.org/national-societies-directory/red-cross-society-panama",
            "hod_first_name": "Martha ",
            "hod_last_name": "Keays",
            "hod_mobile_number": "+507 6330 2770",
            "hod_email": "martha.keays@ifrc.org",
            "assistant_name": "Christian Vega",
            "assistant_email": "christian.vega@ifrc.org",
            "is_ns_same_location": false,
            "is_multiple_ifrc_offices": false,
            "visibility": 4,
            "created_at": "2024-04-30T09:50:18.656188Z",
            "modified_at": "2024-04-30T09:50:18.656204Z",
            "date_of_data": null,
            "country": {
                "name": "Panama",
                "iso3": "PAN",
                "region": 1
            },
            "dotype": {
                "name": "Regional Office",
                "code": 3
            }
        },

**Comment by k9845** [comment]
@tovari For this, we are currently just showing delegation with type `Country Delegation` but country `Panama` has data for delegation `Regional Office`. Should we show regional office as well?
cc: @udaynwa @samshara

**Comment by tovari** [comment]
Yes, please include all types of offices.

**Comment by udaynwa** [comment]
@tovari , the ICRC's website has been changed. So we need to update the scraping logic to pull the data from the latest website. 

Old website: https://web.archive.org/web/20240623064243/https://www.icrc.org/en/where-we-work

New website: https://www.icrc.org/en/where-we-work

Therefore, we have to re-write the scraping logic. This will take a bit of time. 

cc @samshara @thenav56 @nnjemie

**Comment by tovari** [comment]
> [@tovari](https://github.com/tovari) , the ICRC's website has been changed. So we need to update the scraping logic to pull the data from the latest website.

@udaynwa, unfortunately, they don't have an api to retrieve this information, so we need to modify the scraper to get this info. they offered to have a meeting with the developer team, if that helps?

**Comment by samshara** [comment]
> > [@tovari](https://github.com/tovari) , the ICRC's website has been changed. So we need to update the scraping logic to pull the data from the latest website.
> 
> [@udaynwa](https://github.com/udaynwa), unfortunately, they don't have an api to retrieve this information, so we need to modify the scraper to get this info. they offered to have a meeting with the developer team, if that helps?

@tovari Sure, we’ll adjust the scraper logic to retrieve the required information. If needed, we can set up a meeting to discuss further.  
However, this isn’t an ideal solution, and we may need to explore a better approach in the future.

Created a ticket to address the issue
https://github.com/IFRCGo/go-api/issues/2287
