### ISSUE TITLE
GO Training environment - analyze costs and required resources

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#355]
Would be great to understand the costs and required resources to setup and maintain a Training environment.
This would be a copy of PROD with options of data sync from PROD on demand as well.

The purpose is that users would use this to learn and explore the platform.

So, would be good to see approximately:
- costs of setup
- yearly infra costs
- required resources to setup (hours)
- resources of maintenance (yearly) in hours

**Comment by nanometrenat** [comment]
xref old issue https://github.com/IFRCGo/go-api/issues/1106 re sync'ing configuration data vs transactional data

**Comment by batpad** [comment]
> This would be a copy of PROD with options of data sync from PROD on demand as well.

Is this a fully copy including user data?

When we sync, would it be okay to add any other data people might have added to this "copy of PROD" for testing, etc? Or do we also need to keep testing data people might add as well as pull in new data from prod?

If we want to do a full mirror of production that can be updated (or maybe even automatically synced via db replication), this should be relatively easy. If we need to keep testing data around on this instance and yet sync in new production data, this gets much more complex.

Also, when should this instance update? Should it always just update along-with production updates?

Depending on the answers here, we can talk further and figure out concrete estimates.

**Comment by nanometrenat** [comment]
Definitely worth separating out the database concerns around replication/wiping/inserting-new/combination of:

- site configuration data (e.g. how the field reports are set up, country configuration etc.)
- environment-specific data
- user data (not having to create a new user every time – or having to!, permissions setup, removing personal data, whether the password syncs and the notification settings are the same)
- transactional data/content (e.g. field reports, surge deployments, documents/attachments etc.)
- etc.
I had to manage a bunch of pre-prod (i.e. testing), post-prod (i.e. copy of production but anonymised for demo/training purposes) environments in my old life, including all the fun around database keys etc., so happy to contribute to the conversation if useful.
