### ISSUE TITLE
DREF Superticket feedback (From Marco | 19/12/2023)

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#379]
- [x] #401
- [x] #402
- [x] #403
- [x] #404
- [x] #405
- [x] #408
- [x] #410
- [x] #411
- [x] #412
- [x] #413
- [x] #414
- [x] #415

cc @tovari @marcovvu1

**Comment by udaynwa** [comment]
> In the Plan activities section, transfer the total budget from the Overview (first page). – I don’t see it on the planned interventions part

@marcovvu1 , here, do you mean `Planned Interventions` section? Here in current scenario, we have transferred the total budget from the Overview (first page) as `DREF Allocation`, as you can see in the screenshot attached below: 
<img width="765" alt="Screenshot 2023-12-29 at 16 45 31" src="https://github.com/IFRCGo/go-web-app/assets/72339626/1e86913a-e36d-40fa-92bc-7feaa198d853">

Link of DREF Application (on Staging) to replicate the screenshot : https://go-stage.ifrc.org/dref-applications/267
Let us know if any change is required here.

**Comment by samshara** [comment]
@marcovvu1 
For the following issue
-  https://github.com/IFRCGo/go-web-app/issues/402

Can we just show the uploaded file name? This would be more descriptive as it would allow users to verify the uploaded document even before they open it.
![image](https://github.com/IFRCGo/go-web-app/assets/10930537/52fc8e91-522a-4091-828d-80e7c6410571)

**Comment by udaynwa** [comment]
@anamariaescobar , we noticed that when the DREF is `Imminent`, the `Approximate date of event` is appearing in the export even when the field is left empty in the form. We will send a fix for this tomorrow. 

cc @tovari @samshara @frozenhelium

**Comment by udaynwa** [comment]
@anamariaescobar , the fix is pushed to Staging. 

cc @frozenhelium @tovari

**Comment by anamariaescobar** [comment]
It all looks good!!!

Thank you so much, ready to be pushed to production from my side!!

@tovari @frozenhelium  @udaynwa
