### ISSUE TITLE
On three-w/projects the PPP iframe link changed

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-web-app#429]
On https://go.ifrc.org/three-w/projects page (Global 3W Response) the Pilot Programmatic Partnership (PPP) dashboard link has been changed (and is now broken), it should be replaced to
https://public.tableau.com/app/profile/fdrs/viz/PPPdashboard_16805965348010/1_Overview

**Comment by udaynwa** [comment]
Deployed to production in [v7.0.19 release](https://github.com/IFRCGo/go-web-app/releases/tag/v7.0.19).
