### ISSUE TITLE
Surge pages – links to non-countries are broken

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-web-app#431]
On some Surge pages (like https://go.ifrc.org/emergencies/6646/surge ) there is a Rapid Response Personnel table.
On this table the personnel has a "Deploying Party". In some cases these parties are not countries (but regions or the IFRC itself).
In these cases, if we click to the link, the country page does not show them but simply gives an "Error loading data for the country!".
This should be handled nicer (e.g. showing the region or saying that "sorry, this party has no one matching country to be shown").
![6646](https://github.com/IFRCGo/go-web-app/assets/6050643/3fee31fc-11f3-4833-a23d-4a0b580a50e5)
Thanks @tovari for the catch of the issue.

**Comment by tovari** [comment]
Please remove the link in these cases to prevent users clicking on them. Then we don't need a message either.
These are the cases:
IFRC Africa
IFRC MENA
IFRC Europe
IFRC Americas
IFRC Asia-Pacific
IFRC Geneva

**Comment by szabozoltan69** [comment]
(Maybe we could say: if the 4 first characters of the English name are IFRC, the link is not needed.)
I am not sure if the condition can be placed here: https://github.com/IFRCGo/go-web-app/blob/develop/src/views/EmergencySurge/RapidResponsePerosnnelTable/index.tsx#L154
Maybe a new cellRendererParam is needed for [createLinkColumn](https://github.com/IFRCGo/go-web-app/blob/develop/src/components/Table/ColumnShortcuts/index.ts#L311) to create-link-or-not-when-IFRC.

Now I see a typo also: Perosnnel should be Personnel, it occurs only here:
src/views/EmergencySurge/index.tsx:import RapidResponsePersonnelTable from './RapidResponse**Perosnnel**Table';
as filename here:
src/views/EmergencySurge/RapidResponse**Perosnnel**Table

**Comment by tovari** [comment]
We have the same issue at those emergency pages that are associated with a region as a country. E.g.:
https://go.ifrc.org/emergencies/5425/details


![Image](https://github.com/IFRCGo/go-web-app/assets/68283148/71cc6b9e-ba10-48ac-a1a9-a5b73472b187)


We use to redirect those to the regional page of the region in the past and I think we should do the same.

It doesn't solve the problem of IFRC Geneva in the Surge deployments table though as we have no associated region to organizations in the country table like IFRC and ICRC. Those should not have links.
