### ISSUE TITLE
Surge All deloyments table is limited to ongoing deployments

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#440]
Surge All deployments table (https://go.ifrc.org/deployed-personnels/all) should list all ongoing and past deployments.
At the moment, it is filtered to only ongoing deployments. At the moment it lists only 75 ongoing, but not the over 3000 past deployments.

**Comment by udaynwa** [comment]
Deployed to production in [v7.0.19 release](https://github.com/IFRCGo/go-web-app/releases/tag/v7.0.19).
