### ISSUE TITLE
Assessment form - Component 34 should have only one rating for all component

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#446]
# Behaviour
- User should be able to see `Component #14` with just the title and the description (No rating, no notes, no considerations)
- The description currently visible in `Component #14 A` should be moved to the description of `Component #14`
- There should only be one `Component #34` with the title "Logistics, procurement and supply chain"
- There should be 5 question group in the `Component #34`
    - Logistics management
    - Supply chain management
    - procurement
    - Fleet and transfortation management
    - Warehouse and stock management

# Implementation details
- PER Assessment has a series of `Questions`
- `Questions` are grouped into `Components`
- `Components` are further grouped into `Areas`

### Existing Behavior

- A `Component` has following properties
  - Component number
  - Alphabet
  - Title
  - Description
- A `Component response` has the following properties
  - Rating
  - Note
  - EPI considerations (conditional)
  - Urban considerations (conditional)
  - Climate and environmental consideration (conditional)

### Proposed Behavior

- A `Component` can either be a normal component or a `Parent component`
  (captured by `is_parent` property in `Component`)
- A `Parent component` will only have
  - Component number
  - Title
  - Description
- A `Parent component response` will not capture anything

- There should be a new entity `Question group` with following properties
  - Title
  - Description
- A `Question group` must belong to 1 `Component`
- A `Question` may belong to only 1 `Question group`

### Actions

- Make `Component #14` as a `Parent component`
- Move description from `Component #14 A` to 14
- Find similar components and make them a `Parent component`

- Currently, there are 6 components numbered as 34
- Component with title "Logistics, procurement and supply chain" should remain as a `Component`
- Remaining 5 components should be converted to `Question group`
- Add an endpoint for question group (simlar to `per-formquestion`)

### PER Assessment Form
- [x] #548
- [x] #549

### Next steps

- [x] @frozenhelium to covert the board picture into a behavior document 
- [x] @frozenhelium to create another ticket required for frontend

**Comment by steph-gm** [comment]
<img width="572" alt="image" src="https://github.com/IFRCGo/go-web-app/assets/117759277/6f79441d-c230-448a-856d-180560e99919">
Hi @udaynwa @frozenhelium, maybe I can add some explanation about this component. 
Component 34 "Logistics, procurement and supply chain" has its benchmarks grouped together in several groups, but its behavior is similar to that of all the other PER components. Only one rating for the whole component is needed. The benchmarks (questions) are grouped in 5 groups: 34.A Logistics managament, 34.B Supply chain management, 34.C Procurement, 34.D Fleet and transportation management, 34.E Warehouse and stock management. For each one of this groups, we have several benchmarks with their correspondent notes, but no rating, since the rating is for the whole component 34.

**Comment by frozenhelium** [comment]
Thanks @steph-gm for the clarification!

**Comment by shraeyaa** [comment]
- [x] Component 34 is missing sub-component alphabet:
    34.A Logistics management
    34.B Supply chain management
    34.C Procurement
    34.D Fleet and transportation management
    34.E Warehouse and stock management.


- [x] Description is duplicated in component 14 and 14A. 14A should not have any description. @k9845 

@barshathakuri

**Comment by shraeyaa** [comment]
- [x] PER > Assessment - Component 14 is showing EPI Consideration, Urban Consideration and Climate and Environmental Considerations. It should not be visible on component 14. It should be visible only from 14A.

![image](https://github.com/IFRCGo/go-web-app/assets/54019619/a6d1aedb-2a31-4932-8d14-58fa9666b9e5)

cc @k9845 @shreeyash07

**Comment by shraeyaa** [comment]
- [x] 14(F) should not have any description. Currently, it has a description which has to be removed.
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/32e7a404-cbf5-4582-b238-790345e5916b)

![image](https://github.com/IFRCGo/go-web-app/assets/54019619/4f1a1b85-e96d-4157-95a6-9ad20bda53a3)

cc @udaynwa @k9845
