### ISSUE TITLE
General : Add PER export in table

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#447]
### Comments for Developers
We are assuming the format for the export would be minimal (i.e, no colors, icons, different font sizes, etc). This will be similar to the CSV exports.
### User Stories

1. As an authenticated user I should be able to download data for a PER in Excel format

### Functional Requirements

- [x] IFRCGo/go-api#1999
- Frontend should add a button on the PER listing page (under Accounts page) to do the export
- Frontend should show the status of the export and once it's completed it should allow you to download it (this is similar to DREF exports)

### Old title
General - EXPORT TO EXCEL button: Add a button and functionality on the main list page of the "Account" PER forms tab that allows to download the information of the cycle. This could be done in tabs (overview, assessment, prioritization, workplan) - Template file will be shared

**Comment by steph-gm** [comment]
[Template for GO PER Forms Export.xlsx](https://github.com/IFRCGo/go-web-app/files/13903101/Template.for.GO.PER.Forms.Export.xlsx)

Logged in! Here is the template, let me know if it's OK or if you have any suggestions

**Comment by shraeyaa** [comment]
- [x] In workplan tab, 'Description of component related' and 'Due date' are in the same column because of which data have shifted one right.
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/24bbe254-aaf8-4cfe-936a-f7c4aede43e8)

- [x] In Prioritization tab, no data is reflected on export even though data has been filled in the form.
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/c6bcc6ce-7de6-443a-8b4d-a56d934bd972)

- [x] In assessment tab, Component Description is missing for Component 14 and 34.
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/dc7e58d4-fac1-4440-ade4-0aad6fa81d37)

- [x] In Assessment tab, Benchmark Description data is not being reflected on the export
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/73cbf735-8d09-47cc-84f6-f615ed212679)


cc @k9845 @udaynwa

**Comment by shraeyaa** [comment]
- [x]  Prioritized Component description is missing for component 14 and 34
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/daeff8fc-a274-4867-9844-49d53a73dac1)

- [x] 'Additional Actions' of Workplan tab is not reflected in the export.
- [x] In Workplan tab, the data of 'Supported by' is not being reflected in the export if anything except National society has been selected
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/328c3b47-095e-4973-9d44-6ee6bbf1bd35)

cc @udaynwa @k9845

**Comment by shraeyaa** [comment]
- [x] Data of 'Supported by' and 'Supporting National Society' has swapped.
- [x] Title 'Supporting National Society' and 'Status' are in the same column. It should be in different 
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/553b5309-140c-4046-ae3a-99fdc79e7c14)

cc @udaynwa @k9845

**Comment by shraeyaa** [comment]
- [x] I think we need a column for Component letter, in the Workplan tab also.

![image](https://github.com/IFRCGo/go-web-app/assets/54019619/273be9cf-3e1a-4aed-bfed-6b562b51e3a8)

cc @k9845

**Comment by shraeyaa** [comment]
- [x] In Workplan tab, data of Additional actions has shifted one left.
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/e7185b68-102d-40b6-afb4-d099940e0897)
cc @k9845 @udaynwa

**Comment by shraeyaa** [comment]
- [x] 'Benchmark Notes' column on Assessment tab is missing.
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/e809986f-7765-42f4-ad75-e72120063b5a)
cc @k9845 @udaynwa

**Comment by tovari** [comment]
feedback from @steph-gm:

Assessment tab:
•	Add the complete benchmark number (for example 1.1., 1.2.... 2.1, 2.2.... 3.1, 3.2... etc.). At the moment only one number is appearing, so it can be complicated to identify them without relating them to the component number.
![image](https://github.com/IFRCGo/go-web-app/assets/68283148/110510d4-2bca-4453-86e2-36e948d993fe)

Proritization tab:
•	Description of component 34 is missing, as well as descriptions of components 14.A to 14.N -description of those components should appear if they were selected.
•	Component 14 as itself should not appear. This is linked to a situation to be fixed that I detail in the last point (Prioritization form in Production), because 14 has no rating or should be selected in prioritization.
![image](https://github.com/IFRCGo/go-web-app/assets/68283148/6c16df07-69ce-44d5-803e-3445fca63ba9)

**Comment by samshara** [comment]
> feedback from @steph-gm:

> Proritization tab: • Description of component 34 is missing, as well as descriptions of components 14.A to 14.N -description of those components should appear if they were selected. • Component 14 as itself should not appear. This is linked to a situation to be fixed that I detail in the last point (Prioritization form in Production), because 14 has no rating or should be selected in prioritization. ![image](https://private-user-images.githubusercontent.com/68283148/316928406-6c16df07-69ce-44d5-803e-3445fca63ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTc1OTUsIm5iZiI6MTcxMTUxNzI5NSwicGF0aCI6Ii82ODI4MzE0OC8zMTY5Mjg0MDYtNmMxNmRmMDctNjljZS00NGQ1LTgwM2UtMzQ0NWZjYTYzYmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA1MjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMzA1YTUyM2YwM2U4Y2E0Nzg2NzFhNDY5MTZhMjAxMTQ3MzM3MGRmY2E0NjhiNjZjM2I1MDY5OWNmMTIwZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qxfZjdk1A1UXqc3YjEbIL744HgKg0TfMNP0vLXxxpf0)

@tovari @steph-gm  we have removed the description from component 34, and sub-components of component 14 taking the reference from [PER assessment guide](https://drive.google.com/file/d/1WTaGu4-3E0nUvzbIMUjigmk9DgHz7frQ/view?usp=sharing). Do we have an updated guide that we can follow? If the description is required, we also need those descriptions.

**Comment by samshara** [comment]
> feedback from @steph-gm:
> 
> Assessment tab: • Add the complete benchmark number (for example 1.1., 1.2.... 2.1, 2.2.... 3.1, 3.2... etc.). At the moment only one number is appearing, so it can be complicated to identify them without relating them to the component number. ![image](https://private-user-images.githubusercontent.com/68283148/316928221-110510d4-2bca-4453-86e2-36e948d993fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTg0NDEsIm5iZiI6MTcxMTUxODE0MSwicGF0aCI6Ii82ODI4MzE0OC8zMTY5MjgyMjEtMTEwNTEwZDQtMmJjYS00NDUzLTg2ZTItMzZlOTQ4ZDk5M2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA1NDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyYzgyOWE4YzlkZjU1YThkMjI2NDI3YjI5MDY5ZTRjZGNlNDRhZGE0OWE2YTRjMzhjM2MwNzg3NDdhZTE1YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m9-Pp1xCiEu5nPkef45UE-9AH3D3c5MQmszryEe2lWk)
> 
> Proritization tab: • Description of component 34 is missing, as well as descriptions of components 14.A to 14.N -description of those components should appear if they were selected. • Component 14 as itself should not appear. This is linked to a situation to be fixed that I detail in the last point (Prioritization form in Production), because 14 has no rating or should be selected in prioritization. ![image](https://private-user-images.githubusercontent.com/68283148/316928406-6c16df07-69ce-44d5-803e-3445fca63ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTg0NDEsIm5iZiI6MTcxMTUxODE0MSwicGF0aCI6Ii82ODI4MzE0OC8zMTY5Mjg0MDYtNmMxNmRmMDctNjljZS00NGQ1LTgwM2UtMzQ0NWZjYTYzYmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA1NDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NGEyOGY1MzFkZDlhNGYxNDQ0N2U4NDgwYjJmN2NiZjViNDYwYmUzN2VjY2RkMWZkNzNmNDMwOWQwMjhhMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.THs3paiKqPlveMRDvAbQY5my0L2qUag66_T_Bst0BQ8)

Tickets tracking these issues

- [ ] https://github.com/IFRCGo/go-api/issues/2081
- [ ] https://github.com/IFRCGo/go-api/issues/2083

**Comment by steph-gm** [comment]
@samshara sorry about this, you are totally right. The PER assessment guide is correct, there is no description in component 34 nor subcomponents 14.
The only aspect to be corrected then regarding the Prioritization tab would be to remove the component 14, just as referenced above (https://github.com/IFRCGo/go-api/issues/2081)
Thanks!
