### ISSUE TITLE
PER country page - Add PDF export

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#448]
### Old title
PER country page - EXPORT TO PDF button: Add a button and functionality to create a PDF of the visuals on the country page, in particular for the private one

### User Story
1. As an authenticated user I should be able to export the PER Country page view (Preparedness tab) as a PDF

### Functional Requirements
- [x] IFRCGo/go-api#1998
- Frontend to create a new export page for PER Country Preparedness tab
- Frontend to add a button to create a PDF export
- Frontend to download the exported pdf

**Comment by shraeyaa** [comment]
- [x] The x-axis labels of Total Benchmark Summary are missing in PDF export but it is visible in NS Preparedness page under Components by Area.
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/c1050738-ad33-4690-a193-3c477555255c)

![image](https://github.com/IFRCGo/go-web-app/assets/54019619/55620ff3-11ae-4ce6-9fb6-36b1fa93f0ea)

cc @udaynwa @barshathakuri

**Comment by tovari** [comment]
feedback from @steph-gm:

- [x] Add the name of the National Society at the top of the document.

- [x] On the pie chart, add the percentage for each portion of the pie.
- [x] On the highlighted top rated components, add the number of the component next to the name of the component.
- [x] Add the graphic that compares the cycles (the visual named "NS Response Mechanism Performance").

**Comment by tovari** [comment]
- [ ] The page break might cut the visualization. e.g. on page 6-7 : https://dsgofilestorage.blob.core.windows.net/api/pdf-export/PER%20Costa%20Rica-preparedness-Assessment%20(2024-03-26%2015-33-05).pdf
![image](https://github.com/IFRCGo/go-web-app/assets/68283148/96f0948e-4b97-488a-9b37-5a9776eec03b)
