### ISSUE TITLE
PER Country Page - Add the button to upload documents in the country page Preparedness Section for authorized users

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#450]
### User Stories
1. As an authorized user, I should be able to upload and delete a document under country preparedness
2. As a user, I should be able to see the uploaded documents

## Functional Requirements
- [x] IFRCGo/go-api#1994
     -  API endpoint for adding document
     -  API should accept PDF, Excel, and Word format documents
     -  For each country a maximum of 10 documents, with each document being less than 10MB
 - [x] IFRCGo/go-api#1995
 -  Frontend to provide UI to upload and delete the document for authorized users only
 -  Frontend to list the uploaded documents and add a hint or disclaimer indicating the document limits

### Old title
PER Country Page - Add the option/button to upload documents in the private country page Preparedness Section

**Comment by shraeyaa** [comment]
I think we need a confirmation box popup before deleting any uploaded documents.
cc: @barshathakuri

**Comment by shraeyaa** [comment]
- [ ] NS Preparedness and Response Capacity's PER cycle is not visible for unauthorized users. However, when the user enters the URL for the PER cycle directly, the page shows up.
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/4782d8c7-a15b-4e6e-b40a-b1db832f0033)
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/854130ed-e6c2-45cb-a200-6e235782d294)

cc: @barshathakuri

**Comment by tovari** [comment]
feedback from @steph-gm:

•	The uploaded documents should be per cycle, at the moment they are visible for all cycles when uploading it in one particular cycle -but to be checked with the PER team since in any case they would upload documents only for the last cycle, so can be revised later on.

**Comment by samshara** [comment]
> he moment they are visible for all cycles when uploading it in one particular cycle -but to be checked with the PER team since in any case they would upload documents only for the last cycle, so can be revised later on.

@tovari ,  @steph-gm how should we proceed with this?

**Comment by steph-gm** [comment]
Hi @samshara, let's go with having the documents per cycle, so the uploaded documents are only visible for the specific cycle in which they have been uploaded.
