### ISSUE TITLE
[PROD] Wording/text updates (spelling, new link)

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-web-app#486]
A few requests please - all are front end spelling/wording/links, so hope it's OK I've put them all in one ticket.

**Catalogue of Surge Services**
- [x] Spelling fix please - several of the Catalogue of Surge Services pages (e.g. [IM](https://go.ifrc.org/surge/catalogue/information-management), [Cash](https://go.ifrc.org/surge/catalogue/cash) and others) have incorrect spelling in the technical competencies section (say "compentencies", should be "competencies")
<img width="233" alt="image" src="https://github.com/IFRCGo/go-frontend/assets/33625192/c5f05450-e274-4194-b68b-6c45182d8dbb">

~~- [ ] Additional link please - [IM Catalogue of Surge Services](https://go.ifrc.org/surge/catalogue/information-management) - please add an additional link in the Technical Competency Framework section - "Information Management" (**above** the existing "Assessment" link)~~ Alice is requesting this to happen via the usual process rather than my ticket  - now logged as https://github.com/IFRCGo/go-web-app/issues/566

**Resources page**
- [x] Update the GO Contacts section on https://go.ifrc.org/resources - Europe Region should no longer be Luis Fanovich, should now be Henk HOFF henk.hoff@ifrc.org
- [x] Data Playbook link in the IFRC Guidance Material section is outdated - should instead link to https://preparecenter.org/toolkit/data-playbook-toolkit-v1/

Thanks!

**Comment by esario** [comment]
I updated the contacts for Europe and MENA as I noticed it can be done from https://goadmin.ifrc.org/en/admin/api/maincontact/

**Comment by szabozoltan69** [comment]
Great catch, @nanometrenat , this compent... mispelling comes out a lot of places:
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/5ce0379f-f35a-4645-98f8-a3efd00fafc8)

**Comment by szabozoltan69** [comment]
Now the to-be-merged code brings:
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/071b7fe5-3065-468e-94d5-82897546c95e)

**Comment by nanometrenat** [comment]
Both look good on https://go-stage.ifrc.org/surge/catalogue/information-management - thanks

**Comment by nanometrenat** [comment]
All good in Production, thanks a million

**Comment by nanometrenat** [comment]
Reopening - I have just seen in GO today that the "compentencies" spelling gremlin is still there in Production in non-English languages.  It was fixed in English but not in other langs.  This is a screenshot of Spanish IM CoS page but this issue is also in other sector CoS pages.

@tovari I am not familiar with how translations are managed so if I should update wording directly somewhere then please let me know the process - thanks a million
<img width="940" alt="image" src="https://github.com/IFRCGo/go-web-app/assets/33625192/04c9981d-a500-4e8c-9924-4675417f45bb">

**Comment by szabozoltan69** [comment]
> Reopening - I have just seen in GO today that the "compentencies" spelling gremlin is still there in Production in non-English languages. It was fixed in English but not in other langs. This is a screenshot of Spanish IM CoS page but this issue is also in other sector CoS pages.
> 
> @tovari I am not familiar with how translations are managed so if I should update wording directly somewhere then please let me know the process - thanks a million <img alt="image" width="940" src="https://private-user-images.githubusercontent.com/33625192/342347804-04c9981d-a500-4e8c-9924-4675417f45bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODM2NzUsIm5iZiI6MTcyMDA4MzM3NSwicGF0aCI6Ii8zMzYyNTE5Mi8zNDIzNDc4MDQtMDRjOTk4MWQtYTUwMC00ZThjLTk5MjQtNDY3NTQxN2Y0NWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA4NTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMzZlYjlmM2FmNjllMmQ1MzE2ZThmNDY4OGRhNGJjNzgzMDFkNDE1Y2E0NzZhNThkNGZlYjQ2YThhOWUyMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.33zYC1aQGs0ulnKiZeXn1BR_hElEaJ8RV4seR8YEL84">

Recently this "spanish compentencies" seems to be ok:
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/5e9125fb-80c0-4e1f-9c62-df748315a5c0)

**Comment by szabozoltan69** [comment]
I found the "compentencies" in the database dump, so it's true that they must be fixed there also (not only in the frontend code's English texts). I am on it...
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/4f67a963-54b2-4c09-9a2e-f62faaf58cd9)

**Comment by szabozoltan69** [comment]
postgres=> select id, value from lang_string where value like '%compentenc%';
...
 27953 | Tiered compentencies describing the knowledge and skills expected of personnel in this sector.
 27954 | Tiered compentencies describing the knowledge and skills expected of personnel in this sector.
(49 rows)
Fixed:

> update lang_string set value=replace(value, 'compentenc','competenc') where value like '%compentenc%';
UPDATE 49
> commit;

![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/b604072e-3d14-45c8-8890-576a49b5afe5)

**Comment by szabozoltan69** [comment]
@nanometrenat hi, fixed in the database of tranlsations also. (Sorry that only now.)

**Comment by nanometrenat** [comment]
Belatedly closing as the typo is now fixed in Spanish/French as well - thanks a million!
