### ISSUE TITLE
Country Profile > Previous Events > Past Events: Add the missing filters and labels

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#498]
## Task description
`Past Events` section is missing `Events` and `Last 10 years` filters. The chart is also missing `People Exposed/Likely Affected` label in Y-axis

## Link to replicate 
https://go-web-ifrc.dev.datafriendlyspace.org/countries/14/profile/previous-events

## Screenshot (UI design)
<img width="1312" alt="Screenshot 2024-01-23 at 14 41 54" src="https://github.com/IFRCGo/go-web-app/assets/72339626/6e699ac9-8dbe-4c58-935b-d6872e8dd2bd">

**Comment by shraeyaa** [comment]
@frozenhelium Please add the label "People Exposed/Likely Affected"

**Comment by tovari** [comment]
Time filter doesn't work correctly due to this:
https://github.com/IFRCGo/go-web-app/issues/500#issuecomment-2117116679
