### ISSUE TITLE
Country Profile > Previous Events > Past Events: Add the missing information in hazard pop-ups

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#500]
## Task description
Hazard pop-ups in the `Past Events` graph are missing the following data:
- Funding
- Funding Coverage

## Link to replicate 
https://go-web-ifrc.dev.datafriendlyspace.org/countries/14/profile/previous-events

## Screenshot (UI design)
Not available

**Comment by udaynwa** [comment]
@frozenhelium to add comment here.

**Comment by frozenhelium** [comment]
@k9845 let's also add `amount_requested` and `amount_funded` to `/api/v2/country/{id}/historical-disaster/`

**Comment by tovari** [comment]
Looks like the data of the event is taken from the field report creation date. It should be the start date of the event instead.

here is a case from Bangladesh:


![Image](https://github.com/IFRCGo/go-web-app/assets/68283148/8b208df9-943d-49d0-b2c1-315713ccbca9)

and the related event:
https://go.ifrc.org/emergencies/6871/details
