### ISSUE TITLE
National Society Overview > Context and Structure: Add National Society Income Over Time and Income Source Breakdown sections

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#501]
## Task description
GitHub ticket with Google Colab link and findings: https://github.com/IFRCGo/go-web-app/issues/334

## Link to UI design
https://www.figma.com/file/myeW85ibN5p2SlnXcEpxFD/IFRC-GO---UI-Current---1?type=design&node-id=16692-151367&mode=design&t=rJpF3Ev4eOD29MOE-4

## Screenshot (UI design)
![image](https://github.com/IFRCGo/go-web-app/assets/72339626/eed5273a-72b0-4a31-a794-b3ac117b7aa5)

**Comment by shraeyaa** [comment]
National Society Overview > Context and Structure > National Society Income Over Time - Cannot click on different available years other that 2019 (default)
@frozenhelium 
cc: @udaynwa

**Comment by frozenhelium** [comment]
@shraeyaa Should be fixed now!
