### ISSUE TITLE
Country Profile > Previous Events: Add Key Figures (stats) section

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#502]
## Task description
Currently the Key Figures section in `Previous Events` page is missing. Please look into this and add it. 

## Link to replicate 
https://www.figma.com/file/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?type=design&node-id=82-28111&mode=design&t=V6ddXR1jthCGM0Rr-4

## Screenshot (UI design)
<img width="1101" alt="Screenshot 2024-01-23 at 15 00 25" src="https://github.com/IFRCGo/go-web-app/assets/72339626/2245a85d-165f-4dc6-81ff-bb8a9f0d3d2f">

**Comment by frozenhelium** [comment]
@k9845 let's add more info in the `/api/v2/appeal/aggregated/`

#### Current response
```
{
    "active_drefs": 0,
    "active_appeals": 0,
    "total_appeals": 12,
    "target_population": null,
    "amount_requested": null,
    "amount_requested_dref_included": null,
    "amount_funded": null
}
```

#### Expected response
```
{
    "active_drefs": 0,
    "active_appeals": 0,
    "total_appeals": 12,
    "target_population": null,
    "amount_requested": null,
    "amount_requested_dref_included": null,
    "amount_funded": null,

    "total_drefs": 20,
    "total_target_population": 400000,
    "total_amount_requested": 4325000000,
    "total_amount_funded": 782123000,
}
```

**Comment by frozenhelium** [comment]
@k9845 Change of plans:

Lets create a new end-point to get those numbers

**Comment by k9845** [comment]
@frozenhelium Updated with `api/v2/xountry/{country.id}/figure/`

**Comment by tovari** [comment]
Please update the values as described in #918.
