### ISSUE TITLE
Surge CoS - document update

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#505]
A couple of documents to be updated in the catalogue of services, this time in the cash section https://go.ifrc.org/surge/catalogue/cash . 

Can you replace the existing the CVA Coordinator and CVA Officer profiles with the versions attached? 
[Rapid Response Profile Cash and Vouchers Assistance Coordinator 12.2023.pdf](https://github.com/IFRCGo/go-web-app/files/14020697/Rapid.Response.Profile.Cash.and.Vouchers.Assistance.Coordinator.12.2023.pdf)
[Rapid Response Profile Cash and Vouchers Assistance Officer 12.2023.pdf](https://github.com/IFRCGo/go-web-app/files/14020698/Rapid.Response.Profile.Cash.and.Vouchers.Assistance.Officer.12.2023.pdf)

**Comment by tovari** [comment]
There are further requests @szabozoltan69 : 

some more updates needed to documents in the catalogue. This time for the CEA section https://go.ifrc.org/surge/catalogue/community-engagement 

We want to remove all three existing profiles:
•	Community Engagement and Voucher Assistance Coordinator
•	CEA Officer (Accountability)
•	CEA Officer (Risk Communication and Community Engagement - RCCE)

And replace them with just the two profiles attached: 
•	CEA Coordinator
•	CEA Officer

Can we also replace the CEA Competency framework with the new version attached?
[Rapid Response Role Profile CEA Coordinator 12.2023.pdf](https://github.com/IFRCGo/go-web-app/files/14023803/Rapid.Response.Role.Profile.CEA.Coordinator.12.2023.pdf)
[Rapid Response Role Profile CEA Officer 12.2023.pdf](https://github.com/IFRCGo/go-web-app/files/14023804/Rapid.Response.Role.Profile.CEA.Officer.12.2023.pdf)
[CEA Surge Competencies 2023.pdf](https://github.com/IFRCGo/go-web-app/files/14023805/CEA.Surge.Competencies.2023.pdf)

**Comment by szabozoltan69** [comment]
Will look like this, with the new URL-s:
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/063a9c43-14b7-4bb3-9616-3a2b4dd7cdca)

**Comment by nanometrenat** [comment]
Xref https://github.com/IFRCGo/go-web-app/issues/486

Question to @tovari , do the Catalogue of Surge Services competency frameworks and JDs not normally sit on IFRC Sharing these days?  Wondering if they can't just be replaced there (where they are replacements)?

**Comment by tovari** [comment]
Sharepoint links are tricky. They are attached to a file, so even when we use the same doc title, the sharing link might change.

> Xref [#486](https://github.com/IFRCGo/go-web-app/issues/486)
> 
> Question to [@tovari](https://github.com/tovari) , do the Catalogue of Surge Services competency frameworks and JDs not normally sit on IFRC Sharing these days? Wondering if they can't just be replaced there (where they are replacements)?
