### ISSUE TITLE
Country Profile > Overview: Add Seasonal Calendar

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#506]
## Task description
GitHub ticket with Google Colab link and findings: #336 

### Link to UI design
https://www.figma.com/file/myeW85ibN5p2SlnXcEpxFD/IFRC-GO---UI-Current---1?type=design&node-id=15913-237922&mode=design&t=sBmS3EcAiaNhc03p-4

### Screenshot
<img width="1138" alt="Screenshot 2024-01-23 at 15 09 13" src="https://github.com/IFRCGo/go-web-app/assets/72339626/7883348f-e73e-4ce7-b8fd-c0c57d56e4d6">

**Comment by shraeyaa** [comment]
The event bar that ends mid-month in Acaps platform covers the full month in our platform. @frozenhelium @k9845 
Acaps:
![Image](https://github.com/IFRCGo/go-web-app/assets/54019619/98016657-5213-4d75-b10f-396477ab401d)


Go: 
![Image](https://github.com/IFRCGo/go-web-app/assets/54019619/1950ef14-1fea-4e58-a3e2-f7fd82768730)

cc: @udaynwa
