### ISSUE TITLE
[PROD] "Oops! Looks like we ran into some issue!" "Unable to preload CSS" issue continues

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-web-app#515]
## Issue
I have had this error message previously in various circumstances, today's issue is when going to a Country page via the search bar.

<img width="958" alt="image" src="https://github.com/IFRCGo/go-frontend/assets/33625192/be973114-b0bf-4583-921f-7488655582d2">

## Steps to reproduce
Go to go.ifrc.org, in the search box put "Eritrea" or "New Zealand" and click on the country result.

You then get taken to the Country page but get an error message

> Oops! Looks like we ran into some issue!
> Unable to preload CSS for /7.0.17/asset-index-98a34c63.css

With a button to Go back to homepage and a button to reload.

Today I have been finding that I can reload fine - but if I close my browser window then open a new one and follow the same steps I get the same message again.

I'm using Chrome 120.0.6099.217 and am logged in to GO.

## Expected behaviour
*Please describe how this feature should be working.*

## Related feature
Page should load

## Impact
This error message happens quite often for me, in various circumstances (often straight after a release but not always).
GO looks like it's broken.

## Severity
If I hit reload it's fine.

## Is there a workaround?
Reload the page.

**Comment by nanometrenat** [comment]
(also, is this the repo that I should be logging front end tickets in?  Or are we now using go-web-app?  Just let me know how I should know where to put it - thanks!)

**Comment by nanometrenat** [comment]
Same for when I go to the Surge homepage then click through to Catalogue of Surge Services
<img width="848" alt="image" src="https://github.com/IFRCGo/go-frontend/assets/33625192/053f414a-bae3-4c41-b9df-16480df5a4a4">

**Comment by batpad** [comment]
@frozenhelium I know we've been blocked on some Azure stuff in trying to ensure all the CDN caches and browser caches are correctly cleared when we do a new deploy.

Could you take a moment to write what the current situation is, what we need to do to fix this, and what support we might need here? I have noticed weird issues as well for a little bit after deploys and I think we should treat this issue as a bit MUST FIX. Happy to pull in @geohacker to look at CDN cache busting if we need to.

**Comment by nanometrenat** [comment]
xref:  https://github.com/IFRCGo/go-frontend/issues/2667 (may or may not be related)

**Comment by batpad** [comment]
@nanometrenat thanks again for filing this.

What we know so far:

We can definitely reproduce this / know the root cause for the scenario when you have GO open in a browser window, and there's a code update that happens. Subsequent page navigations will fail until you reload once (because it is trying to fetch code chunks for the new page from a location / version that's no longer valid). A single reload should fix that scenario.

However, that does not explain the bit where you say "but if I close my browser window then open a new one and follow the same steps I get the same message again.". If you are able to reliably reproduce this, could we get on a call? The only explanation we were able to come up with was intermittent network issues, might this be a possibility?

We **think** we have fixed all the cache issues related to deployments, with the known issue of requiring a single reload if you had GO open when an update happened (which we can ticket a work-around for separately). But if you are reliably seeing the behaviour you describe, then it's possible we are still having some weird issues with the cache / redirecting to new versions of the code. There's a couple of things we could try with the Azure settings, but it would be good to try and confirm the behaviour / root cause / ideally have something that we're able to reproduce.

**Comment by nanometrenat** [comment]
> However, that does not explain the bit where you say "but if I close my browser window then open a new one and follow the same steps I get the same message again.". If you are able to reliably reproduce this, could we get on a call? The only explanation we were able to come up with was intermittent network issues, might this be a possibility?

I haven't had it since logging the ticket - but then I haven't been using GO that much.  Will let you know when I next hit it, and what my experience is.  @tovari if you let me know when releases happen then I can keep a particular eye out then :)  Thanks all!

**Comment by nanometrenat** [comment]
@batpad @tovari just had it again now:
<img width="867" alt="image" src="https://github.com/IFRCGo/go-web-app/assets/33625192/e9ac6b73-33c2-44be-a0ce-a7f633411eb6">
Had opened a new broswer window, gone to go.ifrc.org and clicked on preparedness/global overview.

Note that earlier in the day (post release) I had gone to GO Catalogue of Surge Services with no issue - but then now I've hit this glitch - weird that it's not the first time I'd gone to GO since the release (though it was the first time I'd gone to *this page* since the release)

**Comment by nanometrenat** [comment]
And again - I was in the IM page  , clicked on Satellite Imagery link and got an error; **although this one is not about css so might be different scenario?**
<img width="799" alt="image" src="https://github.com/IFRCGo/go-web-app/assets/33625192/9076493f-d454-4ccd-a486-77816f12633a">
It's fine on re-load

**Comment by nanometrenat** [comment]
And again just now @tovari @batpad @szabozoltan69 - I went to https://go.ifrc.org/surge/catalogue/information-management (straight from my browser bookmarks, not going anywhere else first) and got this error.  I've been to that page already a bunch of times today...
<img width="748" alt="image" src="https://github.com/IFRCGo/go-web-app/assets/33625192/afa8114b-180c-4357-bc48-4168feca8299">
The only difference I can think of is that this time is I was in an incognito Chrome window... not sure if that has anything to do with it?  Also note that this time it took quite a while for the page to load at all.  I got that holding pattern.  Other websites were loading fine though.  I opened the console and could see some 504 errors.

**Comment by udaynwa** [comment]
Hi @nanometrenat , thanks for the detailed info. We are actively working on this. We hope to resolve this soon.

**Comment by frozenhelium** [comment]
@nanometrenat @tovari this issue should be fixed in the [staging](https://go-stage.ifrc.org/) now. It shouldn't appear from now on (i.e. It still might appear for the current one v7.0.30, but shouldn't appear in the next one)

**Comment by frozenhelium** [comment]
This issue has been fixed, as we have removed all the redirects from the configuration and previous version can be run without getting the chunk error. @tovari We can close this issue now.

![2024-03-04-135523](https://github.com/IFRCGo/go-web-app/assets/4931541/54b6ecea-3c3e-4075-a40d-bf91281fcc73)

**Comment by nanometrenat** [comment]
@tovari I am closing this issue now, haven't seen the gremlin for a while.  Thanks!
