### ISSUE TITLE
[Staging] Aligning SectorLists to backend

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-web-app#519]
## Issue
There is a change on backend that makes possible to change/add Sectors and SectorTags: https://github.com/IFRCGo/go-api/issues/1693
According to that we should avoid using constants on frontend, like https://github.com/IFRCGo/go-frontend/blob/develop/src/root/utils/constants.js#L23-L200
Maybe the color representation could be a new column in backend [table](https://dsgocdnapi.azureedge.net/static/database/tables/deployments_sector.html).
There are endpoints to scan the values on staging (and will be on prod later):
https://dsgocdnapi.azureedge.net/api/v2/primarysector
https://dsgocdnapi.azureedge.net/api/v2/secondarysector

**Comment by szabozoltan69** [comment]
Endpoints are ready:
![kép](https://user-images.githubusercontent.com/6050643/224344180-f82627a4-0a1e-4e2e-a6ca-fdd2d6b1d9d0.png)

**Comment by tovari** [comment]
Is this still to be resolved @szabozoltan69? Thanks.

**Comment by szabozoltan69** [comment]
@tovari @frozenhelium Well, I am not sure wether it is resolved.
At least, what I see, that in the https://goadmin-stage.ifrc.org/api/v2/global-enums/ there is no "sectors" (neither primary, nor secondary).
There is "Wash" e.g. in  "deployments_eru_type", but I would like to ask a frontend developer, if this is used for "sectors".
In src/utils/constants.ts there is no more wired-in "sectors" either.

**Comment by frozenhelium** [comment]
@szabozoltan69 We're using `/api/v2/primarysector` endpoint to fetch the sectors. So, this issues should be resolved now.
