### ISSUE TITLE
SURGE Historical Open Alerts

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-web-app#522]
When making the bulk import of historical deployments into Molnix, a related Alert was created on the Molnix side. Currently we are ingesting this Alerts whit next to none useful information.
We have agree that these alerts must be filtered out, to solve this, a new Tag has been created in Molnix called "No GO", Molnix developers will attach this tag to every position created during the historical data migration.
We need to filter out any position that has this tag attach.
This tag might be useful in the future for other cases.

@batpad @szabolcsgajerifrc @tovari @udaynwa

**Comment by szabozoltan69** [comment]
Sanjay's first hints (thanks): Here we can add a bit: https://github.com/IFRCGo/go-api/blob/develop/api/management/commands/sync_molnix.py#L396
Let's have an is_nogo function, which checks the tags and return True if it has the NO GO tag, and then we just skip to the next one if its a NO GO.
(Also a one-time cleanup is required on database level.)
