### ISSUE TITLE
National Society Overview > Context and Structure > National Society Indicators: Create disaggregation chart for staff and volunteers

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#554]
## Tasks description
- Disaggregation chart should appear in a tooltip when click on `i` icon. 
- Disaggregation chart appears for the stats:
  - Staff
  - Volunteer

### Screenshot of tooltip
![image](https://github.com/IFRCGo/go-web-app/assets/72339626/80460aaa-6ba5-46ff-b23f-2b3316dbf686)

### Link of UI design
https://www.figma.com/file/myeW85ibN5p2SlnXcEpxFD/IFRC-GO---UI-Current---1?type=design&node-id=15913-232062&mode=design&t=NE8BjqKFckYuWmV6-4

**Comment by shraeyaa** [comment]
The Disaggregation chart for staff and volunteers crops out of screen. @frozenhelium 
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/fb713dc5-9552-4fa9-b533-6b33ebfbd430)
cc: @udaynwa

**Comment by shraeyaa** [comment]
Disaggregation chart for staff and volunteers crops out of screen. @frozenhelium 
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/fb713dc5-9552-4fa9-b533-6b33ebfbd430)

cc: @udaynwa
