### ISSUE TITLE
Surge CoS - new document - IM competency framework

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-web-app#566]
Hi there,

Logging in Daniel's absence - we have approval from Alice in Surge.

May you please add a new document to the IM section https://go.ifrc.org/surge/catalogue/information-management

Please add the attached to the Technical Competency Framework section, with the label "IM".  Please also keep the current Assessment framework link (IM should be _above_ Assessment).

[IM Technical Competency Framework_v1.pdf](https://github.com/IFRCGo/go-web-app/files/14169971/IM.Technical.Competency.Framework_v1.pdf)

Thanks!

**Comment by szabozoltan69** [comment]
Will be like this:
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/80d6d00e-88fd-4467-8182-adc4aef2b383)
Uploaded document is here: https://ifrcorg.sharepoint.com/:b:/s/IFRCSharing/Ebz7vm6VjlNAifhse_vLmXQBxGSqF7VytmtmPFiZwUeXgw

**Comment by nanometrenat** [comment]
Looks good on https://go-stage.ifrc.org/surge/catalogue/information-management, thanks a lot

**Comment by nanometrenat** [comment]
Looks good in Production, THANK YOU!
