### ISSUE TITLE
Country profile> Overview > Country Key Indicator: Display `life expectancy` and `literacy` data

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#571]
## Task description
`Life expectancy` and `Literacy` data are displaying in API, but not in frontend

### Screenshots
- In frontend
![image_720](https://github.com/IFRCGo/go-web-app/assets/54019619/8e09b367-0c12-4d82-9a4e-0cb31552b75f)
- In external source
![image_720](https://github.com/IFRCGo/go-web-app/assets/54019619/9e482325-cf09-4a7f-b7ee-2b280cfdf96f)
- In API
![screenshot_2024-02-02_at_11 25 44___am_720](https://github.com/IFRCGo/go-web-app/assets/54019619/eb551e3c-e338-4614-a286-fbab679e1100)

**Comment by tovari** [comment]
It looks like, it is not on the UI yet: https://go.ifrc.org/countries/27/profile/overview

**Comment by udaynwa** [comment]
Might be related to #1170
