### ISSUE TITLE
[PROD] Ordered list of Operations does not show correct operations

### ISSUE THREAD

**Issue by toffehoff** [IFRCGo/go-web-app#612]
## Issue
When I look at the overview of operations on the Europe Region page, there is a currently a three-page list. This looks good. When I now order on Type of Appeal, I see the same amount of operations, but some are missing and some are double. 

## Steps to reproduce
*Go to this page: https://go.ifrc.org/regions/3/operations
Scroll down to the list under the map
Look for the DREF for Iceland (you will find it)
Sort on the column Type of Appeal
Look for the DREF for Iceland (you won't see it)*
[Bug GO Operations ordering.docx](https://github.com/IFRCGo/go-web-app/files/14293943/Bug.GO.Operations.ordering.docx)

## Expected behaviour
I want to see the same list of operations (although differently ordered)

## Related feature
*Please cross-reference the build item to which this relates, if known/relevant*

## Impact
All users who are looking at the Operations Overview

## Severity
GO is not showing correct data. Impact severe.

## Is there a workaround?
Don't use the ordering... But if you don't know what is wrong ... It is not really a workaround.

**Comment by udaynwa** [comment]
@tovari , we are not able to replicate this on our end. Could you please check this on your end? 

Here are some screenshots from our observations
- Before applying filter
<img width="1364" alt="Screenshot 2024-02-16 at 14 49 54" src="https://github.com/IFRCGo/go-web-app/assets/72339626/cd4bb6c1-1b99-4bcd-986b-ade23bc89f77">
<img width="1368" alt="Screenshot 2024-02-16 at 14 49 47" src="https://github.com/IFRCGo/go-web-app/assets/72339626/104b4f53-0573-4e35-9eee-17c26e31fa22">
<img width="1362" alt="Screenshot 2024-02-16 at 14 49 38" src="https://github.com/IFRCGo/go-web-app/assets/72339626/07e08988-37b8-4f22-aa79-4e7aaef6adbc">

- After applying filter
<img width="1365" alt="Screenshot 2024-02-16 at 14 50 25" src="https://github.com/IFRCGo/go-web-app/assets/72339626/d3e523d3-6b2c-451e-90a7-e286ba4dfd43">
<img width="1359" alt="Screenshot 2024-02-16 at 14 50 17" src="https://github.com/IFRCGo/go-web-app/assets/72339626/2bbae8a6-8e34-4e68-9216-a994b9170ee2">
<img width="1364" alt="Screenshot 2024-02-16 at 14 50 09" src="https://github.com/IFRCGo/go-web-app/assets/72339626/4d263c31-0fd6-4503-bd86-317b4ed302d9">


cc @frozenhelium @samshara

**Comment by toffehoff** [comment]
Hi all, I've tried it again, and it now shows the correct list of operations when I use the column ordering. Strange, since this issue did at least last for 2 days. A colleague pointed this out to me. 2 days later this was still the case, also on my laptop. Great that is has magically solved itself. Could this be a caching issue?

**Comment by szabozoltan69** [comment]
This can be a caching issue, yes – or can be also a consequence of "not logged in / logged in" status.
(There was a release on Wednesday, and sometimes cache does not refresh soon enough. Work is in progress about that.)

**Comment by toffehoff** [comment]
FYI, in this case we both (colleague and I) were logged in when this happened.

**Comment by tovari** [comment]
I also checked it before I assigned the ticket and I could also reproduce the error. Now, it works perfectly.
We will need to monitor this in the future.
