### ISSUE TITLE
Turkey in global seasonal risk watch page

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#642]
On the global seasonal risk watch page, under Countries by Risk list, Turkey is displayed instead of Türkiye:

https://go.ifrc.org/risk-watch/seasonal

![image](https://github.com/IFRCGo/go-web-app/assets/68283148/b8653cde-5881-49d5-8085-a9433a58fd91)

Country names in this list should be aligned to GO country names.

cc: @davidmuchatiza

**Comment by k9845** [comment]
Repalced with name `Türkiye`.
