### ISSUE TITLE
"Red Cross" instead of "Red Crescent" on country 3W page toggle buttons

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#649]
Each Red Crescent NS country pages, the 3W tab toggle label incorrectly shows the NS name. It shows Red Cross in every case, even for Red Crescent NSs.
E.g: Egypt Red Crescent:
https://go.ifrc.org/countries/61/three-w/ns-projects

![image](https://github.com/IFRCGo/go-web-app/assets/68283148/22378d65-519a-4d91-9264-562e222370b2)

The correct NS name: Egyptian Red Crescent
So the correct label should be: Egyptian Red Crescent projects

This affects all Red Crescent country pages.

**Comment by frozenhelium** [comment]
@tovari This issue will be deprecated after the changes in the country pages. This is labeled by "3W projects" in new version.

CC: @udaynwa
