### ISSUE TITLE
Context and Structure > Key Documents - File names on the lists are not equal to the pdf title (e.g. AR_UnitedKingdom_2009.pdf when opened, the file name is Anual Report UnitedKingdom 2009.pdf)

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#669]

**Comment by k9845** [comment]
@udaynwa this seems like special case.

**Comment by udaynwa** [comment]
@tovari , this seems to be a special case. Currently, we are showing the document title that we get from the external data source. Once we download it, it shows a different file name. What are your thoughts on this? 

cc @k9845 @samshara

**Comment by tovari** [comment]
@udaynwa, strangely, I don't see these documents anymore on the UK country page. Where can I find Key Documents on the admin page?

**Comment by udaynwa** [comment]
@tovari thanks for flagging this. We will verify this once we deploy the regular cronjobs work related to #1170 

cc @samshara
