### ISSUE TITLE
Surge CoS: Drones – Uncrewed Aerial Vehicles (UAV) Team

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#685]
We need a new section under Others:
https://go.ifrc.org/surge/catalogue/other

_Text on the card:_
**Drones – Uncrewed Aerial Vehicles (UAV) Team**
An Uncrewed Aerial Vehicle (UAV) Team, or colloquially a “Drone” Team, collects high quality, detailed aerial imagery for communications media, mapping, site survey, and situational awareness.

_Please create the content of the new page as it is in the attached document:_
[Catalogue of Services - UAV Team.docx](https://github.com/IFRCGo/go-web-app/files/14407064/Catalogue.of.Services.-.UAV.Team.docx)
_Photos should be on the top of the page similarly as for example here: https://go.ifrc.org/surge/catalogue/health/eru-clinic_

_At the end please add the new role profile as well:_

**Rapid Response Personnel Role Profile**
Details about the expectations for this specialty can be found in the
[Role Profile - Pilot in Command and UAV Team Lead](https://ifrcorg.sharepoint.com/:b:/s/IFRCSharing/EVJrxE_3BpxOliHeThEBk_oB3nAcku47-5BxA-sXV2s8YQ?e=l3FaxQ)

**Comment by szabozoltan69** [comment]
In local dev environment it looks like:
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/02cf3e07-bcaa-482c-8bca-176f02693a47)
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/60e64d55-9212-4fd3-97ad-612a53e4893e)
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/8bb5487f-cb3e-47cc-92a9-8a3b7b26b11b)

**Comment by szabozoltan69** [comment]
Seems to be OK on Staging:
https://go-stage.ifrc.org/surge/catalogue/other/uav
