### ISSUE TITLE
Field report form - Contact details fields should be optional

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#767]
Users reported that recently (since the rewrite), field report form requires to fill all type of contact detail of a contact (name, position, email, phone).
Contact details should not be mandatory.

There is another problem as well. In case text added and then cleared from all contact details fields (name, position, email, phone), the form still gives an error saying the contact details are mandatory:
 
![image](https://github.com/IFRCGo/go-web-app/assets/68283148/e991272d-7dcf-49e3-ac5d-fcfac5a740ab)

**Comment by frozenhelium** [comment]
@tnagorra @samshara Let's prioritize and discuss this.

**Comment by tovari** [comment]
Works well again.

**Comment by tnagorra** [comment]
Should we close this?
