### ISSUE TITLE
Surge Alerts - Stood down alerts stay in Open status

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#780]
There are a lot of 'unfilled' alerts from Molnix that are shown as Open in GO. Looks like the status update in GO doesn't happen for some reason. 
E.g.:
Molnix_id: 2772

Molnix api data:

  "id": 2772,
  "created_by": 933,
  "created_from": null,
  "process_id": 7,
  "name": "Security Coordinator 3rd Rotation, Storm Daniel, Libya",
  **"status": "unfilled",**
  "ispublic": true,
  "visibletoapplicants": true,
  "salary": [],
  "opens": "2023-11-10T14:37:52.000000Z",
  "closes": "2023-11-22T15:16:07.000000Z",
  "start": "2023-11-28T00:00:00.000000Z",
  "end": "2024-01-28T00:00:00.000000Z",
  "notes": null,
  "created_at": "2023-11-10T14:28:22.000000Z",
  "updated_at": "2023-12-19T14:17:35.000000Z",
  "country_id": 127,
  "end_permanent": false,
  "applied": 0,
  "withdrawn": 0,

https://goadmin.ifrc.org/api/v2/surge_alert/?molnix_id=2772
            **"molnix_status": "active",**
            "opens": "2023-11-10T14:37:52Z",
            "closes": null,
            "start": "2023-11-28T00:00:00Z",
            "end": "2024-01-28T00:00:00Z",
            "is_active": false,
            **"is_stood_down": false,**
            **"status": 0,
            "status_display": "Open",**
            "operation": "",
            "message": "Security Coordinator 3rd Rotation, Storm Daniel, Libya",
            "translation_module_original_language": "en"
  
cc: @anamariaescobar

**Comment by szabozoltan69** [comment]
We should build in stood-down handling to sync-molnix - recently it does not handle it.

**Comment by szabozoltan69** [comment]
The main question is: why the molnix-side "status": "unfilled" can not be seen on GO side (where "molnix_status": "active")
Maybe the reason is: we ask from molnix only /positions/open, so the other positions (even if they are updated) will not get to our scope?

**Comment by frozenhelium** [comment]
@batpad is this related to https://github.com/IFRCGo/go-frontend/issues/1638#issuecomment-742330436 ?

**Comment by batpad** [comment]
@frozenhelium yes, exactly! thanks much for tracking that down.

Sorry I forgot to post this yesterday - these are the bits in the old code-base that handled this "Stood Down" condition: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/connected/alerts-table.js#L232
