### ISSUE TITLE
[Staging] Country profile > Supporting Partners - IFRC legal status link needs to be updated

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-web-app#786]
## Issue
Currently the IFRC Legal status link links directly to a specific pdf in FedNet - i.e. /PageFiles/255835/List%20States%20with%20Defined%20Legal%20Status%2025.07.2023_ENG.pdf

HOWEVER as IFRC regularly signs new status agreements (a new one is even being signed tomorrow), it's important to link to the relevant FedNet *page* rather than the attached pdf.  Linking to the *page* means that people can also get the list in the relevant language also.

## URL
https://go-stage.ifrc.org/countries/41/profile/supporting-partners

## Related feature
https://github.com/IFRCGo/go-web-app/issues/337

**Comment by samshara** [comment]
@nanometrenat @tovari can you please mention the appropriate link?

**Comment by nanometrenat** [comment]
> @nanometrenat @tovari can you please mention the appropriate link?

Currently it's `https://fednet.ifrc.org/en/support/legal/legal/new-page/` but I think it is being updated to be a more logical URL - will double-check and get back to you.

**Comment by nanometrenat** [comment]
Hi @samshara, the correct URL to link to is:  [https://fednet.ifrc.org/en/support/legal/legal/legal-status/](https://fednet.ifrc.org/en/support/legal/legal/legal-status/)
Thank you!

**Comment by nanometrenat** [comment]
Hi there, the list of legal status countries has now been updated on Fednet - so it's even more important to make sure the URL is the generic one rather than specific to a given pdf.  Thanks

**Comment by nanometrenat** [comment]
Looks good in Production now - so closing (not sure what process is for closing the tickets that are included in a release bundle, please let me know @tovari)  THANKS

**Comment by nanometrenat** [comment]
xref subsequent ticket https://github.com/IFRCGo/go-web-app/issues/1394
