### ISSUE TITLE
Road network, admin names on the local units map

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#843]
We display now the local units on the map as points. Unfortunately, the point cloud is not really useful without visual context:

![image](https://github.com/IFRCGo/go-web-app/assets/68283148/3f248fe9-1941-4f1f-be11-aef132f1e178)

I suggest to create a new mapbox style that displays road network and municipality/admin names on the base map. These should appear only above a certain zoom level (tbd). If possible, greyscale.

**Comment by geohacker** [comment]
This is a good idea @tovari! @davidmuchatiza are you able to create a new style?

**Comment by davidmuchatiza** [comment]
> This is a good idea @tovari! @davidmuchatiza are you able to create a new style?

Let me give it a try on Mapbox Studio.
