### ISSUE TITLE
Add delete local unit functionality

### ISSUE THREAD

**Issue by samshara** [IFRCGo/go-web-app#857]
### Implementation Details
1. This functionality is only accessible to `Local Unit Admin`.
2. Create a `Delete Local Unit` button inside of the `Local Unit Form`  which deletes the local unit once clicked.

### Figma
https://www.figma.com/proto/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?page-id=2%3A68604&type=design&node-id=3856-49130&viewport=2538%2C-1789%2C0.28&t=bOW8frnGS6h41erL-1&scaling=scale-down-width&starting-point-node-id=3856%3A49130&hide-ui=1
### User Story
https://docs.google.com/document/d/1fbgCb_KMqWa14oL6wxIU7fO3P--clCFzuIQlC9wYQtk/edit?usp=sharing

**Comment by tnagorra** [comment]
Closing this issue. This will be covered in the local units flow updates.
