### ISSUE TITLE
Show local unit information on Local units map popup

### ISSUE THREAD

**Issue by samshara** [IFRCGo/go-web-app#858]
### Implementation Details
1. When the user clicks on the local unit point on the map, a pop-up should appear showing details about the local unit.
2. When the user clicks on the title of the popup, an `Edit Local Unit` form is opened.

### Figma
https://www.figma.com/proto/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?page-id=2%3A68604&type=design&node-id=3856-49130&viewport=2538%2C-1789%2C0.28&t=bOW8frnGS6h41erL-1&scaling=scale-down-width&starting-point-node-id=3856%3A49130&hide-ui=1
### User Story
https://docs.google.com/document/d/1fbgCb_KMqWa14oL6wxIU7fO3P--clCFzuIQlC9wYQtk/edit?usp=sharing

**Comment by shraeyaa** [comment]
Moved to In progress because the Title of the popup is not clickable for now

**Comment by shraeyaa** [comment]
Making new ticket after behavior has been discussed thoroughly

**Comment by davidmuchatiza** [comment]
Closing this one since there is a new ticket addressing the similar issue.

**Comment by davidmuchatiza** [comment]
Closing this one since there is a new ticket addressing the similar issue.
