### ISSUE TITLE
Surge Catalogue of Surge Services updates

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#892]
There are a few updates the team was hoping you could support us with: 
1.	Could we move all the "Additional Services" sitting under the tab "[Other](https://go.ifrc.org/surge/catalogue/other)" so that they each appear directly in the left menu? As such, we should see the following services added to the left menu (in alphabetical order) and the "Other" section deleted:
a.	Civil Military Relations (CMR) – also add acronym 
b.	Disaster Risk Reduction (DRR)
c.	Human Resources (HR) – also add acronym 
d.	International Disaster Response Law (IDRL) – also add acronym
e.	Migration
f.	National Society Development (NSD) – also add acronym
g.	Partnership and Resource Development (PRD) – also add acronym and capitalize letters 
h.	Preparedness for Effective Response (PER)
i.	Recovery
j.	Green Response (GR)
k.	Drones – Uncrewed Aerial Vehicles (UAV) – also remove word "Team" from section title 
l.	Other – remove section
2.	Under the "[Human Resources (HR)](https://go.ifrc.org/surge/catalogue/other/human-resources)" section, could we replace the linked documents by the attached updated versions? One is for the Coordinator role profile and the other for the Officer role profile. Apologies, I cannot update them myself in IFRC Sharing as I am using a Canadian RC laptop and the system isn't allowing me editing rights.
[Rapid Response Profile Human Resources Coordinator 04.2024.pdf](https://github.com/IFRCGo/go-web-app/files/15131490/Rapid.Response.Profile.Human.Resources.Coordinator.04.2024.pdf)
[Rapid Response Profile Human Resources Officer 04.2024.pdf](https://github.com/IFRCGo/go-web-app/files/15131493/Rapid.Response.Profile.Human.Resources.Officer.04.2024.pdf)

4.	Under the "[Livelihoods and Basic Needs (LBN)](https://go.ifrc.org/surge/catalogue/livelihood)" section, could we add the acronym (LBN) in the title and add a box under the sub-section "Rapid Response Personnel" and to the right of the box "Role Profiles"? 
a.	Box name: Technical Competency Framework
b.	Box description: Tiered competencies describing the knowledge and skills expected of personnel in this sector.
c.	Document to link: Livelihoods and Basic Needs Technical Competency Framework – see attached document to upload to IFRC Sharing and link
[Livelihoods and Basic Needs Technical Competency Framework 08.2020.pdf](https://github.com/IFRCGo/go-web-app/files/15131486/Livelihoods.and.Basic.Needs.Technical.Competency.Framework.08.2020.pdf)

**Comment by szabozoltan69** [comment]
Are there some defined icons for these titles?
The existing ones have their from https://github.com/IFRCGo/go-icons:
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/f13aab07-f4a4-43d1-8045-6411aa49115d)
Until the design gets ready, for the development time I put such a question mark to the icons' place:
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/f5376b78-bf2d-4863-ab23-4b59b5d58744)

**Comment by szabozoltan69** [comment]
So like:
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/7f22eb23-91d4-4869-b6ac-6ac244fdb0b7)

**Comment by tovari** [comment]
Good point. We don't have at the moment. I suggest to add temporarily the same icon as we have now at Other and we will replace them when icons will be available. Thanks!

**Comment by szabozoltan69** [comment]
Some icon suggestions:
[icons.zip](https://github.com/IFRCGo/go-web-app/files/15145757/icons.zip)
But I'll continue with the "Other" three-dots icon temporarily.

**Comment by tovari** [comment]
We have now the icons to use:

[CoS.zip](https://github.com/IFRCGo/go-web-app/files/15249580/CoS.zip)

**Comment by szabozoltan69** [comment]
Could you please help me, @samshara @frozenhelium ? How should I inject these icons into https://github.com/IFRCGo/go-icons ?

**Comment by samshara** [comment]
@szabozoltan69 I will be adding these icons to the go-icons library and share with you an update.

**Comment by samshara** [comment]
@szabozoltan69 Please upgrade the `@ifrc-go/go-icons` library to the latest version to use those icons.
To get the names of the icons, please refer to https://github.com/IFRCGo/go-icons/pull/57/files

NPM link: https://www.npmjs.com/package/@ifrc-go/icons/v/1.3.4
Release notes: https://github.com/IFRCGo/go-icons/releases/tag/v1.3.4

**Comment by szabozoltan69** [comment]
Thanks for these, @samshara !

I [included](https://github.com/IFRCGo/go-web-app/pull/926) them to the CoS webpage.

Some comments for name fixes:
StrategicPrioritiesResourceMobilizationIcon ->
StrategicPartnershipResourceMobilizationIcon ?

HumanResource ->
HumanResources ?

DisasterRiskReductionIcon and StrategicP*ResourceMobilizationIcon is a bit grayer (or lighter) than the others.

From EarlyRecoveryIcon and EarlyRecoveryTwoIcon I choose the first, because EarlyRecoveryIcon was not recognizable for me. (Was it intended for Recovery?)

**Comment by szabozoltan69** [comment]
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/05057920-fa1f-429b-bf87-eca0e2a9df6c)

**Comment by samshara** [comment]
> Thanks for these, @samshara !
> 
> I [included](https://github.com/IFRCGo/go-web-app/pull/926) them to the CoS webpage.
> 
> Some comments for name fixes: StrategicPrioritiesResourceMobilizationIcon -> StrategicPartnershipResourceMobilizationIcon ?
> 
> HumanResource -> HumanResources ?
> 
> DisasterRiskReductionIcon and StrategicP*ResourceMobilizationIcon is a bit grayer (or lighter) than the others.
> 
> From EarlyRecoveryIcon and EarlyRecoveryTwoIcon I choose the first, because EarlyRecoveryIcon was not recognizable for me. (Was it intended for Recovery?)

@szabozoltan69, I will have a look it and try to fix them.

**Comment by tovari** [comment]
Thanks @szabozoltan69 , @samshara. Recovery, DRR and SPRM icons were from a different icon set and indeed those are too detailed to show them in this tiny scale. I suggest to use the following instead:
DRR:

![rain-umbrella](https://github.com/IFRCGo/go-web-app/assets/68283148/d4384f55-39da-49af-8993-aac1e0c1e8ab)

Recovery:
![recovery](https://github.com/IFRCGo/go-web-app/assets/68283148/a125d81c-41ea-4592-a526-1e7d0a354d5b)

SPRM:
![Partnership](https://github.com/IFRCGo/go-web-app/assets/68283148/d847f8a2-feb2-4a7d-b959-ba1fcd8a66fc)

**Comment by samshara** [comment]
The icon for SPRM and CEA is the same. Is it okay ? @tovari

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-web-app/issues/1280 for a subsequent icon change
