### ISSUE TITLE
Surge CoS update 03.05.

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#913]
Please update the Partnership and Resource Development (PRD) section. The following changes are needed:
•	Change title section for Strategic Partnerships and Resource Mobilisation (SPRM). This will need to be changed in the left menu as well as on the actual page when we select this section out of the left menu. 
•	Remove the two role profiles currently linked under the Rapid Response Personnel Role Profile section and replace them with the attached updated versions. 
•	Change the layout so that the role profiles appear in a box (see example below, taken from the Operations Management section).
 
[Rapid Response Profile Strategic Partnerships and Resource Mobilisation Officer_final 18.03.24.pdf](https://github.com/IFRCGo/go-web-app/files/15200188/Rapid.Response.Profile.Strategic.Partnerships.and.Resource.Mobilisation.Officer_final.18.03.24.pdf)
[Rapid Response Profile Strategic Partnerships and Resource Mobilisation Coordinator_final 18.03.24.pdf](https://github.com/IFRCGo/go-web-app/files/15200189/Rapid.Response.Profile.Strategic.Partnerships.and.Resource.Mobilisation.Coordinator_final.18.03.24.pdf)

**Comment by szabozoltan69** [comment]
How do you like this result? (The line break in the left menu break is automatic, coming from design.)
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/535cbd9d-50f5-4ac9-a5dc-4b57dd2400a4)
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/e6778e04-cbab-4fd3-a7ce-0ca303b4d064)
