### ISSUE TITLE
[PROD] Incorrect GNI/Capita figures

### ISSUE THREAD

**Issue by clementinebac** [IFRCGo/go-web-app#917]
## Issue
The figures for the GNI/Capita on country pages (under Country Profile > Overview) are incorrect. I suspect that they are the GNI figures rather than the GNI/capita figures.

Taking Burkina Faso as an example:
GNI figures can be found here - https://data.worldbank.org/indicator/NY.GNP.MKTP.CD?locations=bf
GNI per capita figures can be found here - https://data.worldbank.org/indicator/NY.GNP.PCAP.CD?year_high_desc=true&locations=BF

The GO country profile is here: https://go.ifrc.org/countries/181/profile/overview

The figure displayed on GO for GNI/Capita seems identical to the World Bank figure for GNI.

The issue is visible on all the country pages that I have visited.

@tovari

**Comment by samshara** [comment]
@tovari Do we rename it to `GNI` or do we fetch `GNI/Capita` ?

**Comment by tovari** [comment]
@samshara, please fetch the GNI/capita figures.

**Comment by tovari** [comment]
@clementinebac, would you mind to check, if this is correct now on Prod? If it is fine, please Close this ticket.
