### ISSUE TITLE
[PROD] Incorrect numbers of past appeals displayed on country pages 

### ISSUE THREAD

**Issue by clementinebac** [IFRCGo/go-web-app#918]
## Issue
The number of past DREF Operations/Emergency Appeals displayed on country pages (under Country Profile > Previous events) is sometimes incorrect.

## Example
On the Angola country page here - https://go.ifrc.org/countries/18/profile/previous-events

Go to "Last 10 years".

![image](https://github.com/IFRCGo/go-web-app/assets/168839358/de394252-4f8d-4033-8138-d8392f991ea3)

This says that 16 emergency appeals were launched for Angola in the past 10 years. However, according to the following data, only one emergency appeals was launched for the country during that period. Similarly, the figure for DREF is 3 but should be 1.

![image](https://github.com/IFRCGo/go-web-app/assets/168839358/517dc685-4970-42ba-a503-c73408f08d1f)

@tovari

**Comment by tovari** [comment]
I'M not sure, how these values are calculated. As I see there are 12 appeals (6 DREF and 6 EA) since 1996. The latest 3 DREF were in 2009, 2009 and 2023.

**Comment by frozenhelium** [comment]
@tovari lets discuss and document what should be the correct behavior and how to calculate it.

**Comment by tovari** [comment]
@frozenhelium, please take this guideline to calculate values.

Active DREF Operations should be renamed to _DREF Operations_: number of DREF type appeals in the country in the given timeframe
Active Emergency Appeals should be renamed to _Emergency Appeals_: number of EA type appeals in the country in the given timeframe
Targeted Population: sum of the _num_beneficiaries_ figures of all DREF and EA appeals in the country in the given timeframe
Funding requirements:  sum of the _amount_requested_ figures of all DREF and EA appeals in the country in the given timeframe
Funding coverage: (sum of _amount_funded_ figures) / (sum of _amount_requested_ figures) including DREF and EA



cc: @anamariaescobar

**Comment by tovari** [comment]
Also related to #914

**Comment by k9845** [comment]
@tovari For appeals table, we are filtering data on `valid_to` and `valid_from` even after we have filtered on `start_date` and `end_date` . This is the reason we have stats different from that of table. What would be best filteration mechanism here?
cc: @udaynwa

**Comment by tovari** [comment]
Thanks @k9845. How is it filtered for the key numbers section above? Whats the difference in the filtering method?

Also wondering if the valid_to and valid_from are the 'Start after' and 'Start before' filters on the table?

**Comment by k9845** [comment]
@tovari For the key number we filter data based on `start_date` and `end_date` of the appeal and is supplied by the user.
But in Appeals table data are automatically filter on server side base on `valid_to` and `valid_from`..even after we have supplied filter for `start_date` and `end_date` as well. This seems confusing why is this done on Appeal tables.
