### ISSUE TITLE
[PROD] DREF appearing in 2 different Regional pages

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-web-app#957]
## Issue
The DREF MDRHN022 - Honduras - Fire is appearing in two different Emergency pages (Africa and Americas).
## Steps to reproduce

https://go.ifrc.org/regions/1/operations
https://go.ifrc.org/regions/0/operations

![image](https://github.com/IFRCGo/go-web-app/assets/69478743/0490d3f7-88d0-4eae-ab9d-e9aeb7028b47)

## Expected behaviour
This DREF is for Honduras, so it should only be displayed in the Americas Regional page, not the Africa one.

@tovari @szabozoltan69

**Comment by anamariaescobar** [comment]
Little Update: Seems like the issue is that the filter for Africa Regional page is not working (all other Regional pages look okay!)

![image](https://github.com/IFRCGo/go-web-app/assets/69478743/af487a1f-f497-470c-96f0-54ff237c5619)
 
The Africa Regional page is actually showing ALL active operations (108 as of today)

@tovari @szabozoltan69

**Comment by tovari** [comment]
It seems, the Africa page still not filter on the regional appeals:
![image](https://github.com/IFRCGo/go-web-app/assets/68283148/0c6f6ffb-65ff-424e-a40a-cc41b1fb08ba)

**Comment by frozenhelium** [comment]
@tovari It's fixed now on staging!

**Comment by anamariaescobar** [comment]
Looking good from my side in staging!

@frozenhelium @tovari
