### ISSUE TITLE
Apply area component colors (purple, yellow, green, red, blue) on the chart. Design updates have been requested

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#984]

**Comment by mariam-yu** [comment]
@udaynwa and team, here is the prototype for the page: https://www.figma.com/proto/myeW85ibN5p2SlnXcEpxFD/IFRC-GO---UI-Current---1?type=design&node-id=17503-181748&t=MhOMMMgHndLAR0Py-0&scaling=scale-down-width&page-id=16020%3A141452&hide-ui=1
