### ISSUE TITLE
Admin panel: add country and region filters to pending users validation view

### ISSUE THREAD

**Issue by esario** [IFRCGo/go-web-app#999]
## Is your feature request related to a problem? Please describe.
- The number of pending users is quite long (hundreds of users).
- Persons responsible for validating are regional office IM staff, who want to view only the pending users from their region.

## Describe the solution you'd like
I'd like to have a filter at the right side of the admin panel in the [pending users view](https://goadmin.ifrc.org/en/admin/registrations/pending/) that allows me to filter pending users by region and NS, just like I can currently do in the [list of validated users](https://goadmin.ifrc.org/en/admin/auth/user/). 

Both filters have value and shouldn't be seen as alternative solutions: a) region filter is useful when I want to review and approve any pending user from my region, and b) country filter is useful if, e.g., I arrange training to a specific NS, I'd like to filter by country, so that I can then easily validate all pending users from that specific country.

**Filters in users view:**
![image](https://github.com/IFRCGo/go-frontend/assets/15220593/0ddc65bc-e006-4c93-8862-e6ee261ece1e)

**Filters in pending users view:**
![image](https://github.com/IFRCGo/go-frontend/assets/15220593/b73e60cb-d87a-4df7-8be9-86d905227538)

**Comment by szabozoltan69** [comment]
The arriving solution:
![kép](https://github.com/IFRCGo/go-web-app/assets/6050643/78e86003-f945-4222-a096-d1d63bf5cb1e)

**Comment by szabozoltan69** [comment]
Deployed to Staging and Prod.
